### ISSUE TITLE
Chapter 0 first version content

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#1]

**Comment by hupili** [comment]
@ChicoXYC , when you make examples/ screenshots, please use this repository if possible. For jupyter notebooks, you can pick one from: https://github.com/hupili/python-for-data-and-media-communication

**Comment by hupili** [comment]
@ChicoXYC , please keep the following snippet in the footer of every chapter. I added it to week 01 as an example.

```

------

If you have any questions, or seek for help troubleshotting, please [create an issue here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/new)
```

**Comment by rippleYJH** [comment]
@ChicoXYC Just some personal suggestions for you review. 1) can you explain a little bit further why we should preview Jupyter notebook on NBview? Are there any relationship with Github? For a new learner, I think it will be confusing.
2)Can you show how to create an index file in repository? If students don't want to just copy the example, is it possible to show them why (why we need to create an index file? Why is it necessary?) and how? (the procedures of creating an index file)

**Comment by hupili** [comment]
@rippleYJH 

Maybe better for me to explain the concept and @ChicoXYC can add concrete examples and merge my explanations into the open book.

1) One can directly preview a Python notebook on GitHub. However, GitHub prohibits Javascript execution for security reasons. If you have interactive chart, e.g. from `echart`, `plotly`, those will not render on GitHub. NBViewer supports javascript and it is the first free online tool to preview Python notebook, so we recommend it. For concrete examples of dynamic charts, @ChicoXYC can find one notebook from our project archive: https://github.com/data-projects-archive  .

2) Basically, `index.html` is the default file served by the web server. So it is equivalent to visit `example.com` and `example.com/index.html`. Naming your file as `index.html` can lead to this more concise notation in browser's address bar and in communication campaigns -- the naming in the world of web is usually the shorter the better. More explanations are here: https://en.wikipedia.org/wiki/Webserver_directory_index

**Comment by rippleYJH** [comment]
@hupili That will be more clear!!

**Comment by ChicoXYC** [comment]
update @hupili thanks @rippleYJH

**Comment by hupili** [comment]
I added two optional chapters. FYI.

@ChicoXYC  Here are the remaining TODOs:

* [ ] Fix the section headings and check the TOC if the rendered result looks normal.
* [ ] Full proof-reading.

Then we can release to the precamp group.

**Comment by hupili** [comment]
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-00.md#why-we-should-preview-jupyter-notebook-on-nbviewer  -- Not only give the NBViewer link but also give the original GitHub link, so they know what works and what not.
* [ ] `Talking about this function, GitHub is like a cloud disk, which is similar to Google Drive，OneDrive. ` -- Chinese comma.
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-00.md#step-4-commit--publish    -- need to re-take the screenshot. The code in `meta` tag is wrong.
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-00.md#use-github-issue-tracker-as-a-discussion-forum   -- always give URLs if the screenshot is from public domain. In this way, they can see the principle in action. The same for the commit message and all other similar screenshots. Please apply this principle in future work.

**Comment by ChicoXYC** [comment]
@hupili  Update, thanks for your patient instruction.
