### ISSUE TITLE
Restructure book

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#103]
Followup items after the semester:

- [x] @hupili  week 03 breakdown to: 1) control flow; 2) data structure
- [x] @hupili  week 04 breakdown to: 1) serialisation; 2) API
- [x] @hupili  move notes order 1..17.
- [x] @ChicoXYC  Check cross referencing links: is any link broken (due to above restructure)?
- [x] @ChicoXYC Check cross referencing links: revise from absolute to relative if it is internal link.
- [x] @ChicoXYC Update outline.md
- [x] @ChicoXYC  Scan and update FAQs
- [x] @ChicoXYC , update https://github.com/hupili/python-for-data-and-media-communication-gitbook#weekly-notes
- [x] @ChicoXYC , update https://github.com/hupili/python-for-data-and-media-communication-gitbook#faq-catalogue

**Comment by hupili** [comment]
@ChicoXYC , how's this going? Now the chapter is restructured, we can check all cross referencing links.

**Comment by ChicoXYC** [comment]
@hupili 
* fixed invalid URLs and changed the URLs corresponding to the new structure in chapter 0-18.
* changed URLs to the internal URLs if existing in the Openbook
