### ISSUE TITLE
 nbviewer.jupyter.org cannot read the Pyecharts , although used others solution

### ISSUE THREAD

**Issue by CathyChang1996** [hupili/python-for-data-and-media-communication-gitbook#108]
# Troubleshooting

## Describe your environment

*Operating system:MacOS 10.13.6
*Python version: 3.6
*Hardware:MacBook Pro 13-inch, 2017,
*Jupyter notebook or not? [Y/N]:Y

## Describe your question

nbviewer.jupyter.org cannot read my Pyecharts

## Describe the efforts you have spent on this issue

```import pandas as pd
import csv
import datetime
from dateutil.parser import parse
df = pd.read_csv('Billboard Top1 1958-2018.csv')
df['datetime']=df['date'].apply(parse)
describe_song=df.set_index('datetime').resample('1y')['song'].describe()
hhh=pd.DataFrame(pd.to_numeric(describe_song['unique']))
years = list(hhh.reset_index()['datetime'].apply(lambda x: x.year).values)
YN=years[1:]
values = list(hhh.unique.values)
UNI=values[1:]

line = Line("Unique change trend")
line.add("Unique Songs", [str(y) for y in YN], UNI, mark_line=["average"], mark_point=['max','min'])
line.render('line.html')
from IPython.display import IFrame
IFrame('line.html', width=700, height=400)
```

**Comment by CathyChang1996** [comment]
Here is the link:

https://nbviewer.jupyter.org/github/CathyChang1996/python-data-assignments/blob/master/assignment2/Analysis%20of%20%20Billboard%20Hot%20100%20Hits%20(1958-2018).ipynb?jhvuhih

**Comment by hupili** [comment]
You need to commit and push those HTMLs rendered from pyecharts, e.g.

http://github.com/CathyChang1996/python-data-assignments/blob/master/assignment2/Top_10_Aritists.html

`IFrame` will load charts from those files. Those files are actually your charts. You can double click to view them on your local disk.

**Comment by hupili** [comment]
<img width="1193" alt="screenshot 2018-11-25 at 12 34 53 am" src="https://user-images.githubusercontent.com/1227160/48970656-f8aa7680-f049-11e8-8843-61160c17a3e9.png">

**Comment by CathyChang1996** [comment]
I've already solved the problem. Sorry for late response. Thanks a lot!!

**Comment by ChicoXYC** [comment]
Closed.
Similar issues #102 #93 
Please refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-jupyter.md#display-charts-in-nbviwer).
