### ISSUE TITLE
How to find the same string in different lists?

### ISSUE THREAD

**Issue by CathyChang1996** [hupili/python-for-data-and-media-communication-gitbook#117]
# Troubleshooting

## Describe your environment

* Operating system:MacOS 10.13.6
* Python version:3.7
* Hardware: MacBook Pro
* Jupyter notebook or not? [Y/N]: Y

## Describe your question

I have a column in a dataset called 'location', and every row of it is a whole string, I want to transform it into a 'list' and try to find out if there is any overlap strings in different rows. 

How to get this work?😄🤔️

The dataset link is as follows:
https://github.com/CathyChang1996/CathyChang1996.github.io/blob/master/review_mafengwo.csv

**Comment by hupili** [comment]
Quick notes here:

- Use `eval` to turn a Python-notation string of objects into real Python objects
- Use `set()` for set intersection
