### ISSUE TITLE
simplify the bar chart example

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#119]
@ChicoXYC , please remove the palette parameter from our entry level examples. Following appeared very common in student works. Most color gradient in their work does not carry information. We keep it simple as a start.

<img width="1200" alt="screenshot 2018-11-30 at 11 50 22 pm" src="https://user-images.githubusercontent.com/1227160/49299541-ed989000-f4fa-11e8-8369-cf3359cd9401.png">

**Comment by ChicoXYC** [comment]
Update, please see here: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-09.md#basic-usage-1
