### ISSUE TITLE
feedback for Charpter3

### ISSUE THREAD

**Issue by rippleYJH** [hupili/python-for-data-and-media-communication-gitbook#12]
It seems that this week has large load of content! Just some humble suggestions:

1. in the Str Comparison part we give an example: Name1 == Name3, then return the bool value is True. Is it necessary to explain the "equal" true meaning? Since if we try "Name1 is Name3", the result would be False. So the '==' just means the two items have equal content here, doesn't mean they are the same thing.

2. in the List[] part:
A little bit confused about "remove()" and "pop()"...What are the differences? Could you explain in additional lines?

3. in the Dict{} part:

- I noticed we talk about index for several times, like the list.insert(i,x), pop(i)...Maybe it's better to explain more on the index, better to accompany with demonstrating graph and let us see how are the 'identity numbers' match different items, like {1, 2, 3, 4}
                                                           [0][1][2][3]   
-  A typing error: unorder --> disorder
- Sorry for my weak understanding... It seems that the str() format has no difference with the original one (Example10) So why we use str()? It’s better to illustrate~

4.  A tiny question:
> >>> seq = ['Chico', 'Ivy', 'Ri']
>>> dict = dict.fromkeys(seq)  #fromkeys()
>>> print("New_dict : %s" % str(dict))
New_dict : {'Chico': None, 'Ivy': None, 'Ri': None}

#Why the seq be converted to a list? Is it achieved by fromkeys()?

5. >>> for i in range(1,11):
>>>    print(i**2)
#Should we add a footnote that here i**2 can also write as (i * i) ? Maybe that will be more clear for students?

6. 
> >>> if number_of_users <= 50000:
...               cost = 10000

Can we make a warm remind that the indent helps to define which statement is under the "if" control? It's so easy to make mistakes for new learners.

7. 
> The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default).(1,10) means values from 1 to 11 (but not including 6)
#here why not including 6?? Could you explain a little bit?

8.
> >>> i = 1
>>> while i < 9:
>>>     print(i)
>>>     if i == 5:
>>>         break
**>>>     i = i + 1** # why this condition is under the 'break'? As a new learner, I will think all flows go from top to down and when encounter the 'break', the flow will stop there, so may need some explanation.

9. 
> return 'My name is {self.name}, and I'm {self.age} years old'.format**(self=self)** 
- Can we show another format for readers to better understand?
return 'My name is {0}, and I'm {1} years old'.format(self.name, self.age)'
caz I don't understand here: format**(self=self)** ...

10. It is better to tell readers how to call class function. For example, we should call from the class name.

@hupili Can you add some content on instance variables and class variables? I think the "class" part has not been fully developed so it may be confusing. 
Also, in the final example, better to explain the relationship between class method (Account) and  instance method (deposit and withdraw), and how to call these functions.

Thanks for your hard work!

**Comment by hupili** [comment]
> @hupili Can you add some content on instance variables and class variables? I think the "class" part has not been fully developed so it may be confusing.
> Also, in the final example, better to explain the relationship between class method (Account) and instance method (deposit and withdraw), and how to call these functions.

I haven't read the notes yet. @ChicoXYC , as to a common strategy, please try to suppress the discussion of class method/ class variable. It is hard to establish a full concept of OOP, or OOP in Python. To make most of our projects work, we do not have to use classmethod or staticmethod. Just follow the most straightforward use: define class; instantiate it to operate on it.

**Comment by ChicoXYC** [comment]
@rippleYJH Thanks so much! As for your question

1. `is` will return True if two variables point to the same object, `==` will return true if the objects referred to by the variables are equal.
```
>>> 1000 is 10**3
False #they are not the same object, but only values are equal
>>> 1000 == 10**3
True
```
2. You can see the definition in the list table
3. 
```
>>> print("To String : %s" % str(person_dict))
To String : {'Chico': 24, 'Ri': 19, 'Frank': 31}  #it's a string, not the same as original dict
```
4.
```
>>> seq = ['Chico', 'Ivy', 'Ri']
>>> dict = dict.fromkeys(seq)  #get/create keys from the list
```
5. yes, you can.
6. add remind
7. its a type error
8. you can put ahead of `break`, it will only change the sequence of the execution
9. Good! you can write as this. I also add explation of self=self and why we use this
10. It'a a little bit different and confusing for us now, maybe we can add it to the further reading

**Comment by rippleYJH** [comment]
Detailed explanation, much clear now, many thanks~ @ChicoXYC
