### ISSUE TITLE
Add pyecharts.WordCloud example to week 10

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#120]
[pyecharts.WordCloud](https://pyecharts.org/#/zh-cn/charts_base?id=wordcloud%EF%BC%88%E8%AF%8D%E4%BA%91%E5%9B%BE%EF%BC%89)  can be added as an alternative method in tag cloud viz of week 10. The benefit is to get rid of matplotlib Chinese issue.

**Comment by ChicoXYC** [comment]
Added into notes, please refer here:https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-10.md#wordcloud-with-pyecharts
