### ISSUE TITLE
Add sort_by more than 1 columns with different ascending/ descending

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#121]
[This example](https://nbviewer.jupyter.org/github/ZhangHuimin97/python-data-assignments/blob/master/assignment2/analysis.ipynb#2.In-a-sense,-the-amount-of-comments-shows-the-popularity.-But-if-we-want-to-find-a-cheap-room-with-higher-popularity,-what-we-will-do?) is good.

<img width="1202" alt="screenshot 2018-12-01 at 12 33 11 am" src="https://user-images.githubusercontent.com/1227160/49301972-ccd33900-f500-11e8-972b-5d213af274a1.png">

Please add to week 7 the sort values part.

**Comment by ChicoXYC** [comment]
multiple sort_values already exist in the week 7. with the following usage:

```
df.sort_values(['likes','bookmark'],ascending=[False,False])
```

**Comment by hupili** [comment]
I [restructured sectioning](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-07.md#sorting-dataframesort_values). The content is intact. Please proof-read and then close the issue.

**Comment by ChicoXYC** [comment]
multiple sorting https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-09.md#sorting-dataframesort_values
