### ISSUE TITLE
Add project information and links to the class page

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#129]
- [x] S2018, can find forked copy here: https://github.com/data-projects-archive/
- [x] F2018, can add their original repo address first. After the final report due date, we fork to data-projects-archive for archiving purpose.
- [x] Add quick reading pointer.

**Comment by hupili** [comment]
For each project entry, we need to add a quick reading pointer. Some readers of that page may not be technology literate. We help them to jump into the very last "final report" directly. Those who want to explore more can checkout the repo for details. Since every repo has different structure, it may take some time to figure out the best reader's file -- it can be a PDF of final report, an NBViewer link, or a word document, or a web page.

In the following example:

<img width="683" alt="screenshot 2018-12-19 at 9 39 22 am" src="https://user-images.githubusercontent.com/1227160/50193625-593f8180-0372-11e9-8409-e55fc36bb919.png">

"Final report without code" would be this "go-to" document.

**Comment by ChicoXYC** [comment]
ok. for f2018, most of them have web pages, it's easy to leave some content guide here, but for s2018, most of them only have ppt, which cannot display directly in GitHub. If there is no better without code version, I will just leave the ppt version link.

**Comment by ChicoXYC** [comment]
update [F2018](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/session-F2018.md#projects)

**Comment by hupili** [comment]
The style can be slightly improved. For example, the two second level bullet point list can be simplified to following links at the end of line.

```
[[Story]](https://catmint1215.github.io/) | [[Codes]](https://github.com/data-projects-archive/201812-BigData-final-project-GoogleAppStore)
```

Rendered as follows:

[[Story]](https://catmint1215.github.io/) | [[Codes]](https://github.com/data-projects-archive/201812-BigData-final-project-GoogleAppStore)

**Comment by hupili** [comment]
This line is in different format. Please unify.

> HK Tourism. Hong Kong visitor analysis: from the perspectives of country/region of residence, mode of transport and consumption expenditure. By XU Manning, YU Lei, SHEN Yue, WONG Pui Lam. [Story] | [Codes]

This is minor issue and you can fix right after get this message. I'll close first.

**Comment by ChicoXYC** [comment]
update. Sorry about that
