### ISSUE TITLE
Hatty's Feedback on Ch3 

### ISSUE THREAD

**Issue by HattyW0724** [hupili/python-for-data-and-media-communication-gitbook#13]
# Hatty's feedback on Chapter 3

### Before advice:

This chapter really surprises me because it is so fruitful, with full of knowledge points about statements, expressions, operators, functions, modules, methods, etc. and even though before reading Ch3 I learned parts of the same fundamental knowledge with a series of simple practices, it's still a tough work to finish all practice and check throughout this chapter.

### Here are some bullet points I think might be useful for you:

* In some parts, one or two sentences to describe what one knowledge point the chapter introduces can serve for real programming in practice. In other words, one or two sentences to provide its meanings.

* Since this chapter is so substantial, fresh learner may feel their brains about to explode if they learn it at a time, so I think it can be better if we separate this chapter into three or four small sections by using, for example, emphasis fonts.

* In the part of "List methods" and Example 7: 
    * Description: more details and no “s” behind every verb
       Examples: separate examples for diverse methods with spaces.
    * Provide some practices behind every part of methods learning.

* More description of While loop, and probably provide a comparison between If loop and While loop so as to allow students to learn about their functions better.

* The exhibition of examples needs some hints. For examples 15 & 16, students may feel confused what the target is to write these while loop codes.

* Repare two small bugs: 
   * In example 13 question, the formula is "cost=1000+0.1×(number_of_users -50000）" .while in the answer : `cost = 10000 + 0.1 * (number_of_users - 50000) ` . 
   * In example 14, 
>  The actual number of users we have now is 120,000. 
    
   should be blended into the question part with grey color font, which will be easier for learners to read.

**Comment by ChicoXYC** [comment]
@HattyW0724 thx a lot.
* add for loop & while loop comparison
* fixed bugs
* examples adjustment
