### ISSUE TITLE
How to display a dynamic chart completely? [pyecharts render relative (percentage) width/ height]

### ISSUE THREAD

**Issue by Jasmine-dudu** [hupili/python-for-data-and-media-communication-gitbook#136]
# Troubleshooting

## Describe your environment

* Operating system: MacOS 10.13.6
* Python version: 3.7
* Hardware: MacBook Pro

## Describe your question

We want to display a dynamic chart related to "Type top 10 apps" (the link: [https://github.com/Jasmine-dudu/Big-Road/blob/master/Type%20top10%20Apps.html](url) ) in the web page. However, we fail to show it completely like a static chart. 

![wechatimg338](https://user-images.githubusercontent.com/42904368/49984518-5ecc4e80-ffa3-11e8-8b08-dc4a9871ea1c.png)
![wechatimg339](https://user-images.githubusercontent.com/42904368/49984520-64299900-ffa3-11e8-82f6-8924ca1d3056.png)

How to solve the problem?😣Great thx!🙇‍♀️

The web page can be found via the link: [https://github.com/Jasmine-dudu/Big-Road/blob/master/index.html](url)

**Comment by hupili** [comment]
@Jasmine-dudu  , here is the solution:

https://nbviewer.jupyter.org/github/hupili/python-for-data-and-media-communication/blob/master/pyecharts-examples/pyecharts-resize.ipynb#Responsive-output-for-pyecharts

When you initialise the pyecharts object, give it a relative width/ height number, e.g. 

```python
chart = pyecharts.Bar(width='100%', height='90vh')
```

The HTML files rendered in this way can fit into Big Road responsive chart area easily.

**Comment by ChicoXYC** [comment]
Closed. Merged this issue into notes, you can refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-11.md#integrated-exercise-publish-a-full-work-in-a-stand-alone-page).
