### ISSUE TITLE
Cannot use spacy.load('zh') to install model for no shortcut link

### ISSUE THREAD

**Issue by ZhangHuimin97** [hupili/python-for-data-and-media-communication-gitbook#137]
# Troubleshooting

## Describe your environment

* Operating system:
cva517
* Python version:
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]:
Y
* Which chapter of book?:
Topic modelling

## Describe your question

Example: I cannot load any packages from spacy.lang. I cannot use shortcut links to find the file. If I set up a link for the model, it will remind me that the meta.json in the file cannot be read.

![2018-12-14 6 22 11](https://user-images.githubusercontent.com/42903809/49997727-50932800-ffcd-11e8-8047-1167ef9552e9.png)

## The minimum code (snippet) to reproduce the issue

Example:

```python
spacy.load('en')
spacy.load('zh')
```

## Describe the efforts you have spent on this issue

Example:

I download a Chinese model from github and have successfully installed it in my current working file. But I cannot link it with spacy. So so sad. crying。。。

link for the model ：
https://github.com/howl-anderson/Chinese_models_for_SpaCy

### What is the closest answer you can find?

**Comment by ChicoXYC** [comment]
@ZhangHuimin97 
does this help? I found this in their test example :https://github.com/howl-anderson/Chinese_models_for_SpaCy/blob/master/test.py
```python
import zh_core_web_sm
nlp = zh_core_web_sm.load()
```

**Comment by ChicoXYC** [comment]
@ZhangHuimin97 has your problem solved?

**Comment by hupili** [comment]
This is too specific. We'll get back if someone else encounter this problem in the future.
