### ISSUE TITLE
failed to open url with urllib.request

### ISSUE THREAD

**Issue by ivyWANG958** [hupili/python-for-data-and-media-communication-gitbook#139]
# Troubleshooting

## my environment

* Operating system: ios
* Python version: 3.7
* Jupyter notebook or not? [Y/N]: Y
* Which chapter of book?: notes-week-07

## my question

I could not open url using `urllib.request` library 

## The minimum code (snippet) to reproduce the issue

```
import urllib.request

with urllib.request.urlopen('http://www.indeed.com/jobs?q=data+scientist&l=') as url:
    source = url.read()
```
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

## the efforts you have spent on this issue

I found a slack issue [SSL Certification error #334](https://github.com/slackapi/python-slackclient/issues/334) have same discussion, but I still could not figure it out.

**Comment by hupili** [comment]
Seems CVA network problem. Do you have the same problem when testing in other places?

**Comment by ivyWANG958** [comment]
> Seems CVA network problem. Do you have the same problem when testing in other places?

Yes, I test at home, the error message is: `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>`

**Comment by hupili** [comment]
It's Ok at my side. It's likely you are behind firewalls.

**Comment by hupili** [comment]
Since this is network problem, you need to bypass the walls on the pathways. Using a proxy will help. `urllib` and `requests` allows to configure a proxy in the parameters. Depending on your network situation, you may find different proxy providers. Just search "HTTP proxy", "SOCKS proxy", etc

**Comment by ivyWANG958** [comment]
> Since this is network problem, you need to bypass the walls on the pathways. Using a proxy will help. `urllib` and `requests` allows to configure a proxy in the parameters. Depending on your network situation, you may find different proxy providers. Just search "HTTP proxy", "SOCKS proxy", etc

Thanks for the pointers, will do accordingly.
