### ISSUE TITLE
Connor's Feedback&Question on Chapter 2 

### ISSUE THREAD

**Issue by ConnorLi96** [hupili/python-for-data-and-media-communication-gitbook#14]
## Feedback
This Chapter is really wonderful. Although I've already got a bit of fundamental knowledge about python from other channel,  I also receive new inspirations and flexible programming usage because it give more practical examples and transmit an important concept-use it in daily life.

Additionally, to be a fresh learner, I also have some suggestions and questions to this Chapter. 

## Suggestions & Questions
* Questions
In the  **Basic functions: Arrays**, I try my best to understand the definition of "shape" but I'm still confused for it, especially in the under example.Hoping to receive a more detailed explanation of the operating rules. Thx!
```python
>>> b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
>>> print(b.shape)
(2, 3)
>>> print(b[0, 0], b[0, 1], b[1, 0])
1 2 4
```

* Suggestions
The under example regards the concept of **index** . However, before this example, there is any introduction about index, which may cause some difficulties to 0 background learners. 

```python
>>> import numpy as np
>>> a = np.array([1, 2, 3])   # Create a rank 1 array
>>> print(a[0], a[1], a[2]) # index elements
```
Thus, I think there are two effective ways.

1. Add the link to the 6th example of Chapter 3, which explain it exactly.
2. Give simple explanation about the index.

**Comment by hupili** [comment]
Thanks @ConnorLi96 ! Clear written feedback. @ChicoXYC can you try to address the comments first? For better explaining certian concept, feel free to ask me. It also helps to link to different reading materials on a certain topic.

**Comment by ChicoXYC** [comment]
@ConnorLi96  @hupili 
Thanks so much. Add explanation of array.shape and index, hope it may be helpful for you. If you have more questions, free to ask.

* Array.shape
```python
>>> b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
>>> print(b.shape)
(2, 3) #the first number means how many elements in this array, in this case, this array has two elements - two lists. The second number means how many sub-elements in each element. In this case, there are 3 values in each list. So, it's like a layer nesting.
>>> print(b[0, 0], b[0, 1], b[1, 0])
1 2 4 #you can access values by their index. Similarly, the first number is to index elements in this array, the second number is to index the sub-elements in each elements.
```
* About index in data types

Simply, `Index` is like the position of one element in the whole list or object, which used to access this element. The index of first element is `0` and increases by integer. The following are examples may help you better understand this.

```
    String  ‘H     e     l      l      o'
    Index   [0]   [1]   [2]    [3]    [4]
    List    ['a', 'b',  'c',   'd',   'e']
    Index   [0]   [1]   [2]    [3]    [4]
```

In the list ['a', 'b', 'c', 'd', 'e'], list[0]='a', 0 is the index of 'a' in this list, similarly use in array. We will use more in chapter 3 so that you can get more familiar with this issue.

**Comment by ConnorLi96** [comment]
Thanks a lot! This explanation is very useful and help me to understand it totally.
