### ISSUE TITLE
prevent feedparser overwrite when scrape rss feed

### ISSUE THREAD

**Issue by ivywze** [hupili/python-for-data-and-media-communication-gitbook#154]
# Troubleshooting

## Describe your environment

* Operating system: iOS
* Python version: 3.6
* Jupyter notebook or not? [Y/N]: Y
* Which chapter of book?: Ch7

## Describe your question

when using _feedparser_ for an element with the same name within one entry, the later one seems to overwrite the former one:

<img width="796" alt="Screen Shot 2019-07-18 at 11 24 18 PM" src="https://user-images.githubusercontent.com/35587993/61471314-25364880-a9b5-11e9-9a21-fb5094bb3914.png">

<img width="819" alt="Screen Shot 2019-07-18 at 11 34 39 PM" src="https://user-images.githubusercontent.com/35587993/61471340-2e271a00-a9b5-11e9-89cf-d2dab562536f.png">

### What is the closest answer you can find?
[Accessing multiple links](https://pythonhosted.org/feedparser/uncommon-atom.html#accessing-multiple-links) -- official doc

But in my case, the entry itself just print one item and ignore the other one.

**Comment by hupili** [comment]
@ivywze , can you share a partial notebook so we can follow up from where you left?

**Comment by MindyZHAOMinzhu** [comment]
I cannot find the same website as Ivy had. Are there any problem with the original format of the website code?

**Comment by ConnorLi96** [comment]
Sorry for reply late, my VPN is failed so cannot access the website. 

I guess you can try to use ```CSS```  and ```Xpath``` to parse it layer by layer, this ```Parse``` is prasing the whole page, maybe ignore part of tags, and I guess show more code would help us to deal with this problem soon.

**Comment by ivywze** [comment]
Thanks all for the effort. @hupili sorry but that's all the code I have regarding this problem. @MindyZHAOMinzhu I think the rss feed format is like this. @ConnorLi96 thanks, I was just trying out that way. 

I will just use another approach, thanks again.

**Comment by hupili** [comment]
@ivywze  how did you solve the original problem? 

p.s. That may help future readers.

**Comment by ivywze** [comment]
> @ivywze how did you solve the original problem?
> 
> p.s. That may help future readers.

Sorry, I didn't solve the problem. I just used other ways to scrape.
