### ISSUE TITLE
Chapter 5 Working thread - basic scraping (static)

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#16]
* [x] @ChicoXYC crawl the whole initiumlab.com -- need iterate the article list by pagination.

**Comment by ChicoXYC** [comment]
@hupili update

**Comment by hupili** [comment]
**BCP**: refrain from text processing if possible, especially in the upstream of data processing pipeline.

After you get the `tr`, you can further find `td`, locate the second `td` and further find the list of `span`s. This way is more stable. The major problem of splitting text is that the delimiter may also appear as part of the text content.

<img width="620" alt="html-find-authors2-output" src="https://user-images.githubusercontent.com/1227160/45200503-aefc8c00-b2a3-11e8-8930-25a0de9b281f.png">

**Comment by hupili** [comment]
Please present the BCP as primary solution and this text-split as an alternative for people to compare.

**Comment by ChicoXYC** [comment]
@hupili update bf96a92.

**Comment by hupili** [comment]
Looks good 👍 . Closing for now. Please note that BCP stands for "Best **Current** Practice"

**Comment by SerenaQYHuang** [comment]
There seems to be a typo in [week05 notes](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md) (The part of HTML language) as follows
![image](C:\Users\Administrator\Documents\WeChat Files\thinmint\Files\screencapture_20180912112648.png)
Isn't a slash missing in the underlined part?
