### ISSUE TITLE
Chapter 7 Working thread - pandas basics

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#18]
* [x] @hupili outline.
* [x] @ChicoXYC prepare an updated openrice dataset of similar format. **High Priority**. Please store the scraping script and dataset in the `scraper-example` folders. Create new files and don't override previous openrice example.
* [x] @ChicoXYC include the URL and POI ID of each restaurant into the 20K dataset.
* [x] @ChicoXYC , address the TODO notes for `pandas` basics. Note that there is a bit duplicate between ch7 and ch8 (1D part). This is normal because most of the time you observe errors during analysis. So analysis skills can also help data cleaning.
* [x] @hupili, @ChicoXYC , inject some errors into the openrice dataset for data cleaning exercise.
* [x] @ChicoXYC  First review and smoothen the content up to [dataprep section](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-07.md#dataprep)

**Comment by hupili** [comment]
openrice PR: https://github.com/hupili/python-for-data-and-media-communication/pull/9

**Comment by hupili** [comment]
@ChicoXYC , I just find the [notebook](https://github.com/hupili/python-for-data-and-media-communication/blob/a5985d4bf42ad91536c04c6e2f936118194d44df/scraper-examples/open_rice/openrice_sample.ipynb) contains an exploded row:

<img width="967" alt="screen shot 2018-10-04 at 12 38 59 pm" src="https://user-images.githubusercontent.com/1227160/46453304-703ef080-c7d3-11e8-8fe2-d9a464b2ae01.png">

Is it by design? for data cleaning exercise? Or an error in the scraper?

**Comment by hupili** [comment]
Two more fields are needed for the dataset: @ChicoXYC include the URL and POI ID of each restaurant into the 20K dataset.

I also added this to the checklist in the issue body.

By POI ID, please see this annotation:

<img width="572" alt="screen shot 2018-10-04 at 12 48 54 pm" src="https://user-images.githubusercontent.com/1227160/46453401-ef342900-c7d3-11e8-90a6-3e19fff534ec.png">

It is always good to record the URLs of detail page when you scrape a list page. If you want more detailed information in the future, you can get this information from the detailed page URL.

The POI looks like a useful (and incremental unique ID). We can use it to identify a restaurant. When two restaurant has the same name in different places, the POI is different. In a complete dataset, every row needs to have an ID (or ID that can be derived somehow).

**Comment by ChicoXYC** [comment]
Its an error, not designed.
> @ChicoXYC , I just find the [notebook](https://github.com/hupili/python-for-data-and-media-communication/blob/a5985d4bf42ad91536c04c6e2f936118194d44df/scraper-examples/open_rice/openrice_sample.ipynb) contains an exploded row:
> 
> <img alt="screen shot 2018-10-04 at 12 38 59 pm" width="967" src="https://user-images.githubusercontent.com/1227160/46453304-703ef080-c7d3-11e8-8fe2-d9a464b2ae01.png">
> 
> Is it by design? for data cleaning exercise? Or an error in the scraper?

**Comment by ChicoXYC** [comment]
> Two more fields are needed for the dataset: @ChicoXYC include the URL and POI ID of each restaurant into the 20K dataset.
> 
> I also added this to the checklist in the issue body.
> 
> By POI ID, please see this annotation:
> 
> <img alt="screen shot 2018-10-04 at 12 48 54 pm" width="572" src="https://user-images.githubusercontent.com/1227160/46453401-ef342900-c7d3-11e8-90a6-3e19fff534ec.png">
> 
> It is always good to record the URLs of detail page when you scrape a list page. If you want more detailed information in the future, you can get this information from the detailed page URL.
> 
> The POI looks like a useful (and incremental unique ID). We can use it to identify a restaurant. When two restaurant has the same name in different places, the POI is different. In a complete dataset, every row needs to have an ID (or ID that can be derived somehow).

OK, noted

**Comment by ChicoXYC** [comment]
@hupili 
- update 30ks dataset with two more fields, link and poi_id
- pandas basics

**Comment by hupili** [comment]
The content density of this one looks appropriate. You start to get the feel. I place some TODO markers in the ch7's file. Please revise.

**Comment by ChicoXYC** [comment]
@hupili 
* finish all to-dos
* add data cleaning exercise

**Comment by hupili** [comment]
@ChicoXYC need to change [this](https://github.com/hupili/python-for-data-and-media-communication-gitbook/commit/58315803dcb9c7d2507c9eddb497cf06eac86114#diff-a61fa44b17203213878070a50bfa7a97R817) to our code repo once the PR is merged. After that, this working thread is good to close. Let's keep working on more data cleaning cases.
