### ISSUE TITLE
Chapter 8 Working thread - 1D analysis & 2D analysis

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#19]
* [x] @ChicoXYC organise from S18 notes, 1D and 2D analysis.

**Comment by ChicoXYC** [comment]
Oct 31th
* [ ] @ChicoXYC update Variance,Skewness,Kurtosis
* [ ] @ChicoXYC distribution & filter
* [ ] @ChicoXYC Calculate basic correlation

**Comment by ChicoXYC** [comment]
@hupili 
I have some problem to ask for help, thanks in advance:
1. do I need put the `advanced` correlation part (better vasualization part and filter the outliers in the graphs) of the last semester demo into notes?

2. don't really know why the `rank` results is like this, though I checked out the `series.rank function`. Dose it shoud be the rank of the scores? in that case, what does those values means?
<img width="312" alt="screen shot 2018-10-31 at 9 41 10 pm" src="https://user-images.githubusercontent.com/37010763/47791924-c9a82a00-dd55-11e8-9341-444f9f06c57c.png">

**Comment by ChicoXYC** [comment]
1101 
* [ ] @ChicoXYC  The last todo in this phrase: Cross-tab and correlation.
@hupili Is there anything that has higher priority? please let me know.

**Comment by hupili** [comment]
> do I need put the advanced correlation part (better vasualization part and filter the outliers in the graphs) of the last semester demo into notes?

Yes, as bonus section. The highest priority is to tidy up past materials. If they are too advanced, I can move and edit. But don't miss out, or we lose track of the content.

> don't really know why the rank results is like this, though I checked out the series.rank function. Dose it shoud be the rank of the scores? in that case, what does those values means?

You can make a simpler Series yourself and observe the result. It is easier to observe smaller ones than the large dataset.

**Comment by hupili** [comment]
@ChicoXYC , you can list out all pending TODOs regarding ch8 first, so I can evaluate the priority.

**Comment by ChicoXYC** [comment]
@hupili Update. All issues related to chapter 8 has been update. If there is anything need further modified, please let me know.
- [ ] Cross-tab and correlation
- [ ] Tidy up past materials
