### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by hakutoccino** [hupili/python-for-data-and-media-communication-gitbook#24]
In Example 6, there are lines following:

>>> test = [0]
>>> print(test,'is',bool(test))
[0] is False

However, in my and my Python's opinion, the result should be true. Am I right?

**Comment by ChicoXYC** [comment]
@hakutoccino @hupili My fault, this is `true`, someone also gave me this feedback, thanks!!!
the reason why its true is because `test` is a list which has a value - 0, it's not equal to 0, or none or empty.  It has a true value, thus, its true. hope this can help you better understand!
