### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by hakutoccino** [hupili/python-for-data-and-media-communication-gitbook#27]
in the Example 13:

>>> test3 = 'python loves,\'you\''
>>> test3.find('you')
8 #returns the first character where 'you' begins

Is that should be 8? I think it may be 14 instead?

**Comment by ChicoXYC** [comment]
@hakutoccino thanks so much! You are right. The correct answer is 14.
Kindly remind, next time, please specify which chapter so that we can communicate more effectively. Thanks again.

**Comment by hakutoccino** [comment]
@ChicoXYC welcome! sorry I forgot that _(√ ζ ε:)_
