### ISSUE TITLE
How to create a file in "example" repository

### ISSUE THREAD

**Issue by Fiiiiiiish** [hupili/python-for-data-and-media-communication-gitbook#29]
# Troubleshooting

## Describe your environment

* Operating system:mac os
* Python version:
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]:
* Which chapter of book?:week00

## Describe your question

week00- gh desktop
How to create a file in "example" repository after create a new repo. 
don't understand the "drag"part.  _Thank you!_

<img width="959" alt="2018-09-06 17 07 04" src="https://user-images.githubusercontent.com/42933069/45147384-612a4a00-b1f7-11e8-9034-176303dd14f1.png">

**Comment by ChicoXYC** [comment]
@Fiiiiiiish 
1. make sure you download the text editor - visual studio code.
2. Find the repository/folder you just created, you can click `open this repository in finder` to know its file path. After you find the folder, drag the repository/folder into the text editor.
3. create a new `.md` file by the text editor, and write several words in it and save it.
