### ISSUE TITLE
Chapter 2 Working thread

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#3]

**Comment by bonnie-yu** [comment]
- Need to change all the print syntax to Python 3 version. For Python 3, the print statement should be enclosed in parentheses, like `print("XXX")`.

- typo: caculate-->calculate
![screen shot 2018-07-30 at 9 44 00 am](https://user-images.githubusercontent.com/35587764/43371918-01ad2c00-93de-11e8-8a35-e5a3a6252f18.png)
![screen shot 2018-07-30 at 9 43 18 am](https://user-images.githubusercontent.com/35587764/43371919-096c516e-93de-11e8-9d54-b81d9e77f0b5.png)
![screen shot 2018-07-30 at 9 44 24 am](https://user-images.githubusercontent.com/35587764/43371920-0c0d7204-93de-11e8-836c-1d73e0f4a461.png)

- For eg3, the `red = 0` is missing. Btw, will it be a better expression to say"it will print red in terminal" below eg4 to keep same sentence structure and avoid confusion.
![screen shot 2018-07-30 at 9 59 13 am](https://user-images.githubusercontent.com/35587764/43372137-e0aca4ce-93e0-11e8-8931-bdf84242fc35.png)

-  maybe better to write the outcome as "A = 262500"
![screen shot 2018-07-30 at 9 46 18 am](https://user-images.githubusercontent.com/35587764/43371939-44f2a4ae-93de-11e8-9368-0bc9641a2145.png)

- should it be calculate the area of a circle? round is adjective actually.
![screen shot 2018-07-30 at 10 54 27 am](https://user-images.githubusercontent.com/35587764/43372718-13f41de8-93e7-11e8-8546-43072ab6da39.png)

- feel confused about the $$\sin(\frac{\pi}{6})$$
![screen shot 2018-07-30 at 9 48 52 am](https://user-images.githubusercontent.com/35587764/43371948-75129b62-93de-11e8-922d-3a5cd71c20d5.png)

**Comment by hupili** [comment]
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/outline.md  please check if there are points in outline but not covered in the weekly notes. If so, let's discuss how to add them. The weekly notes from last semester may not completely reflect our teaching objective. It is adjusted based on the class pace. We can cover more in the e-book.
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-02.md#challenge   Think of more ideas of challenges -- some practical problems that may be solve by the mere knowledge from this chapter. We can bounce ideas and discuss on Slack channel before moving to the public book. -- one good example is your "business planning" calculator. Give brief descriptions and pointers.
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-02.md#exercise-1-simple-calculation  change from Python2 to Python3 notation, e.g. `print ...`. Make sure you have executed all those codes in your Python3 console.

**Comment by hupili** [comment]
* [ ] a minor glitch -- a non-printable character

<img width="581" alt="screen shot 2018-08-07 at 9 30 10 pm" src="https://user-images.githubusercontent.com/1227160/43778750-1366f212-9a89-11e8-864d-8c36f46cb31a.png">

**Comment by hupili** [comment]
I finished revising major problems. @ChicoXYC  Please study the following commits and incorporate in future notes:

* 3ae61a0c87e89efb458cc4144241cb6d828dd707  -- Put the discussion under more contexts. It is never too clear for the description. Always keep on sharpening the presentation and test with other users.
* a3f68561b43a8df62007d71c682d04dec22188c3 -- Give proper details with good relevance. Explain concepts that matter. This is not mandatory as you are also a beginner. Just give your best try and always check the revised version. For example, the file layout (`__init__.py` things) and the way to write a function is important in this discussion. You can give pointers to those interested minds but avoid them in the main body.
* 02a6fba84600f16ab63ce9399f10d33b9d4affdb -- Just a bit aesthetics.

I also have some detailed comments in the commits. I will release the lecture note right away, but please keep on revising and make sure the latest version is always the best whenever the user checks.
