### ISSUE TITLE
Instructions of Installing Jupyter Notebook on Windows

### ISSUE THREAD

**Issue by kaiwenxu94** [hupili/python-for-data-and-media-communication-gitbook#30]
### How to install virtual environment and Jupyter Notebook on Windows
**Trouble description**
The Jupiter tutorial(module-jupyter.md) lacks instructions for Windows 10 users like me, and yesterday it took me almost two hours to figure out how to install virtual environment and Jupyter Notebook on my laptop, as the codes to input are different than those in Linux. Hence, I have written down the instructions to install virtual environment and Jupyter. I think it will be helpful for Windows users if the following content can be added into the tutorial.

**Instructions**
You need to create virtual environment as well to use Jupyter Notebook if your operating system is Windows. However, the codes you need to input are a little bit different than those in Linux.

1. Create a folder named 'venv'. You can place it wherever you like, be it disk C, D or E. In this case, I put it in disk D.

2. Press Windows key+R, which shows you the 'RUN' box. Input `cmd` and click 'OK'.

![image](https://user-images.githubusercontent.com/42831899/45152742-85405800-b204-11e8-9f96-48d219207666.png)
![image](https://user-images.githubusercontent.com/42831899/45152760-8b363900-b204-11e8-96d1-c51eaf68b68b.png)

3. Input `D:` to change to disk D.
![image](https://user-images.githubusercontent.com/42831899/45152866-d4868880-b204-11e8-9061-4a6194a252d3.png)

4. Input `cd venv` to go to the 'venv' folder.
![image](https://user-images.githubusercontent.com/42831899/45152908-eec06680-b204-11e8-8c5c-74f66f89d306.png)

5. Enter `python -m venv test`, so you create a virtual environment called 'test', and you can see the newly created 'test' folder.
![image](https://user-images.githubusercontent.com/42831899/45152921-fa139200-b204-11e8-8b6d-95ec7dfefe67.png)
![image](https://user-images.githubusercontent.com/42831899/45152935-00097300-b205-11e8-92d2-be8a6699a99b.png)

6. Enter `cd test` to go to the 'test' folder.
![image](https://user-images.githubusercontent.com/42831899/45152951-0bf53500-b205-11e8-910c-945fb0f0c55d.png)

7. Input `cd Scripts` to go to the 'Scripts' folder.
![image](https://user-images.githubusercontent.com/42831899/45152965-16173380-b205-11e8-969d-c70dfae77b58.png)

8. Input `activate.bat`. Now you can see (test) appear in front of the command line prompt, it means you have entered the virtual environment!
![image](https://user-images.githubusercontent.com/42831899/45152980-20d1c880-b205-11e8-8978-2cc2ffd2a510.png)

9. Enter `pip install jupyter`  to install jupyter.
![image](https://user-images.githubusercontent.com/42831899/45152999-30511180-b205-11e8-858b-584a29138645.png)

10. Input `jupyter notebook` to launch jupyter notebook.
![image](https://user-images.githubusercontent.com/42831899/45153015-3cd56a00-b205-11e8-98e6-597dbc3f074e.png)

11. Press 'Ctrl+C' two times to quit the Jupyter notebook, and input `deactivate` to exit virtual environment.
![image](https://user-images.githubusercontent.com/42831899/45153039-49f25900-b205-11e8-9f01-47080ae6c1c0.png)

12. So next time you need to enter the environment and launch jupyter notebook, here are all of the codes you need to input in cmd.exe in order.
![image](https://user-images.githubusercontent.com/42831899/45153071-5bd3fc00-b205-11e8-944e-e4bc0aafe62c.png)

**Comment by NicoleZZC** [comment]
<img width="240" alt="default" src="https://user-images.githubusercontent.com/42857182/45260684-4555bc80-b420-11e8-8b71-b2bbb0f1bf41.PNG">
Help! why it comes the info above when I tried to create the virtual environment?

**Comment by NicoleZZC** [comment]
Got it! THX @ChicoXYC
