### ISSUE TITLE
Install Python3 on Windows and Set Environment

### ISSUE THREAD

**Issue by kaiwenxu94** [hupili/python-for-data-and-media-communication-gitbook#32]
1. Click [here](https://www.python.org/ftp/python/3.7.0/python-3.7.0.exe) to download Python 3.7.
2. Remember to choose 'Customize installation' and click 'pip' when you are installing python. If you install the default version, you cannot import 'numpy' module in week2. 
![image](https://user-images.githubusercontent.com/42831899/45255308-2111c580-b3b7-11e8-8371-82c3b687956d.png)
![image](https://user-images.githubusercontent.com/42831899/45255309-253de300-b3b7-11e8-94b8-47f622ece7f9.png)

**Comment by Zmh951010** [comment]
Also I have something to add:
1. when choosing the version of Python, Win10 ×64 bit users can find the relative version here
https://www.python.org/downloads/windows/
![20180702201304982](https://user-images.githubusercontent.com/42828826/45263653-05aec500-b460-11e8-82a8-9752322727d2.png)

2. When installing, we also need to check the "Add Python 3.7 to PATH"
![_20180909183813](https://user-images.githubusercontent.com/42828826/45263667-6211e480-b460-11e8-997f-4f4398fa15a1.png)

**Comment by ChicoXYC** [comment]
**Supplement:**

If you don't add Python version you install into PATH. When you type python in cmd, you will get the following error
```text
不是内部或外部命令，也不是可运行的程序或批处理文件
```
or 

```text
‘python’ is not recognized as an internal or external command
```
 You can solve this problem by add the Python installation path to the environment variable. Please refer to this https://blog.csdn.net/MickeyMouse1928/article/details/70035747

**Comment by hupili** [comment]
@ChicoXYC ,  Once the discussion is organised into corresponding FAQs, please leave a link (better to section level) in the discussion thread before closing issue. In this way, future visitors can directly find the solution, without going through a long list of discussions

**Comment by coolxu8888** [comment]
No matter what, every block I saw, I tick it. LOL

**Comment by AlexZenghuashan** [comment]
![_20180911164635](https://user-images.githubusercontent.com/42838093/45349190-39febe80-b5e3-11e8-9684-bc1cfbcec7af.png)
The Python3.7.0 is for windows(32-bit), mine is windows(64-bit) and i couldn't enter the set up page.

**Comment by Zmh951010** [comment]
@AlexZenghuashan you can go to this page
https://www.python.org/downloads/windows/
and find the correct version here:
![45263653-05aec500-b460-11e8-82a8-9752322727d2](https://user-images.githubusercontent.com/42828826/45349801-dc6b7180-b5e4-11e8-9f6d-b58c793b05cb.png)

**Comment by Catmint1215** [comment]
If you still can not download it, I can send the ".exe" to you directly.

**Comment by AlexZenghuashan** [comment]
![image](https://user-images.githubusercontent.com/42838093/45354877-6e797700-b5f1-11e8-82b9-efedc36fb953.png)
I was told that windows services pack1 and all applicable updates are required to intall python3.70 (64bit), so i downloaded and installed all the things below.
![_20180911180236](https://user-images.githubusercontent.com/42838093/45367981-076db980-b615-11e8-9458-df3c6c02dead.png)
However, it still didn't work!
![image](https://user-images.githubusercontent.com/42838093/45368037-32f0a400-b615-11e8-9a6e-38ad69c0f6b8.png)

**Comment by AlexZenghuashan** [comment]
I have tried all the versons above 3.0. None of them work for me. Finally, I found that python 2.7.12 is ok!
