### ISSUE TITLE
CH05 Feedbacks

### ISSUE THREAD

**Issue by SerenaQYHuang** [hupili/python-for-data-and-media-communication-gitbook#33]
* Operating system:windows
* Python version:3
* Hardware:
* Internet access:Y
* Jupyter notebook or not? Y
* Which chapter of book?:05

Feedback1:
 I got an Error when trying to install BeautifulSoup using the first codes mentioned as follows

<img width="228" alt="1536734298 1" src="https://user-images.githubusercontent.com/41979788/45406583-89072b00-b699-11e8-999d-7c3c7431589b.png">

The output is as follows:

<img width="464" alt="1536734257 1" src="https://user-images.githubusercontent.com/41979788/45406527-6d038980-b699-11e8-957a-dc3375c30744.png">

### Do they solve or partially solve your question? Yes, but in a different way

**Comment by SerenaQYHuang** [comment]
I think there might be a typo here: the underlined text should be 'r' instead of 'resp'

<img width="687" alt="1536734815 1" src="https://user-images.githubusercontent.com/41979788/45406988-bbfdee80-b69a-11e8-889e-0fca0f6096f3.png">

**Comment by ChicoXYC** [comment]
@SerenaQYHuang have you install pip before using pip to install bs4

**Comment by SerenaQYHuang** [comment]
@ChicoXYC After I googled, I found out that I should install pip first. However, new learners may mistakingly think that the codes below are the installation solution. Perhaps it'll be better to state more clearly

<img width="424" alt="1536741595 1" src="https://user-images.githubusercontent.com/41979788/45413029-bb6d5400-b6aa-11e8-9a39-a2b10accd53b.png">

**Comment by SerenaQYHuang** [comment]
Another Typo:

```python
def scrape_one_article(article_url):
    r = requests.get(url).text
    my_page = BeautifulSoup(r,"html.parser")
    my_title = data.find('h1').text.strip()
    my_date = data.find('time').text.strip()
    my_authors = data.find('tr',attrs={'class':"post__authors"}).text.strip().replace('\n',',')
    my_tags = data.find('tr',attrs={'class':'post__tags'}).text.strip().replace(' ','').replace('\n\n\n\n\n','|')
    my_url = article_url
    return my_title,my_authors,my_date,my_tags,my_url
```

Line 2: `(url)` hould be `(article_url)`

**Comment by SerenaQYHuang** [comment]
@ChicoXYC 
```python
articles = []
article_urls = scrape_articles_urls_of_one_page('http://initiumlab.com/blog/') #scrape_articles_urls_of_page1
for article_url in article_urls:
    articles.append(scrape_one_article(article_url))

with open('articles.csv','w',newline='') as f:
    writer = csv.writer(f)
    header = ['Titles','Authors','Dates']
    writer.writerow(header)
    writer.writerows(articles)
```
No output for this piece of code

**Comment by SerenaQYHuang** [comment]
@ChicoXYC 

```python
import requests #week o4 request module
from bs4 import BeautifulSoup #pay attention to its syntax
import csv

def scrape_one_article(article_url):  #scrape one articles features, which we've already done this
    r = requests.get(article_url).text
    data = BeautifulSoup(r,"html.parser")
    my_title = data.find('h1').text.strip()
    my_date = data.find('time').text.strip()
    my_authors = data.find('tr',attrs={'class':'post__authors'}).text.strip().replace('\n',',')
    my_tags = data.find('tr',attrs={'class':'post__tags'}).text.strip().replace(' ','').replace('\n\n\n\n\n','|')
    my_url = article_url
    return my_title,my_authors,my_date,my_tags,my_url

def scrape_articles_urls_of_one_page(article_page_url): #scrape_articles_urls_of_one_page, its a little bit different from demo above because in the following pages(2-7), the articles' urls are different...
    article_urls = []
    r = requests.get(article_page_url).text
    data = BeautifulSoup(r,"html.parser")
    my_urls = data.find_all('a',attrs={'class':'post__title-link js-read-more'})
    for my_url in my_urls:
        url ='{0}blog{1}'.format('http://initiumlab.com/',my_url['href'].split('/blog')[-1]) #format urls.
        # Fail try 1 : use slice to cut off ../../..
        # Fail try 2 : use blog instead of /blog to split. There are blog in the headline
        #print(url)
        article_urls.append(url)
    return article_urls

def scrape_all_pages(url):
    articles=[]
    for i in range(1,8):  #format all pages urls
        if i == 1:
            page_url = url
        else:
            page_url = '{url_initial}page/{number}/'.format(url_initial = url,number=i)
            #print(page_url)

        article_urls = scrape_articles_urls_of_one_page(page_url)
        for article_url in article_urls:
            articles.append(scrape_one_article(article_url))

    return(articles)

with open('initiumlab_articles.csv','w',newline='') as f:
    all_articles = scrape_all_pages('http://initiumlab.com/blog/')
    writer = csv.writer(f)
    header = ['Titles','Authors','Dates','Tags','Url']
    writer.writerow(header)
    writer.writerows(all_articles)
```

No output

**Comment by hupili** [comment]
@SerenaQYHuang  is it because you used conda? conda users run `conda install xxx`.

**Comment by hupili** [comment]
@SerenaQYHuang @ChicoXYC , can you add an FAQ page dedicated to conda? Most students will not experience this path if they follow our initial instructions to install Python3. Their installation will have `pip` or `pip3` by default. In case there are `conda` users, we let them know the difference.

**Comment by ChicoXYC** [comment]
ok @hupili . @SerenaQYHuang can you install by ` conda install xxx`?

**Comment by SerenaQYHuang** [comment]
@ChicoXYC @hupili I use jupyter notebook under Anaconda. And I tried both but none worked

<img width="845" alt="1536835454 1" src="https://user-images.githubusercontent.com/41979788/45483941-08bdf400-b785-11e8-8043-4bcdb6a02c02.png">


<img width="853" alt="1536835388 1" src="https://user-images.githubusercontent.com/41979788/45483903-e6c47180-b784-11e8-8bd7-f11831f881aa.png">

**Comment by hupili** [comment]
it’s

 !conda install

! is to issue shell command

**Comment by SerenaQYHuang** [comment]
As follows...the codes seem to be correct

<img width="688" alt="1536912566 1" src="https://user-images.githubusercontent.com/41979788/45538060-96a6e700-b838-11e8-8e91-76370e9ec334.png">

**Comment by zhangjingwei0512** [comment]
@hupili When I do the further exercise 2 ,I find some questions.
I run the code https://github.com/zhangjingwei0512/chapter5/blob/master/further2.py  three times，
each time I get a different answer(https://github.com/zhangjingwei0512/chapter5/blob/master/further2.csv ，https://github.com/zhangjingwei0512/chapter5/blob/master/further2%EF%BC%881%EF%BC%89.csv，
https://github.com/zhangjingwei0512/chapter5/blob/master/further2(2).csv )
However,none of them are complete.Some informations are omitted.
I suppose there's is nothing wrong in my code,but why the answer is different and uncompleted?

**Comment by hupili** [comment]
please open a new issue for this question. Let’s make the topic threaded. I’ll check later at home

**Comment by hupili** [comment]
@zhangjingwei0512 , we moved to this thread: https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/39

**Comment by hupili** [comment]
Just a note @SerenaQYHuang @ChicoXYC , we keep only MAC solution in the main body of our open book, so people do not see many "if mac do this, elif windows do that" content. To accommodate Windows and Anaconda users, we can have FAQ docs.
