### ISSUE TITLE
An alternative way to calculate the break-even point of subscribed users to make profit in Example21 in Week3

### ISSUE THREAD

**Issue by kaiwenxu94** [hupili/python-for-data-and-media-communication-gitbook#34]
The Example 21 in Week3 tutorial is helpful for us to learn how the For loop works. But I also find that the same result can be achieved with the While loop as well. Below are the codes that I write to share with you guys for reference and suggestions. You can also check the results in nbviewer [here](http://nbviewer.jupyter.org/github/kaiwenxu94/hkbu-big-data-exercises-and-projects/blob/master/python%20exercises/week3/Calculate%20the%20break-even%20point%20of%20subscribed%20users%20to%20make%20profit.ipynb).

```
Fixed_Cost = 30000
Content_Cost = 70000
member_ff = 15
convert_rate = 0.1
ad_revenue_each_person = 1
subscribers=0
net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost
if net_income==0:
	print(subscribers)
else:
	while subscribers>=0:
		subscribers=subscribers+1
		if subscribers<50000:
			net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost
		else:
			net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost-0.1*(subscribers-50000)
		if net_income==0:
			break
print(subscribers)
```

**Comment by hupili** [comment]
@kaiwenxu94 Good try!

A further challenge: try to scale up the parameters by a uniform factor, say `Fixed_Cost = 3000000`, `Content_Cost = 7000000` -- the resulting number of subscribers will scale up similarly. However, it takes much more time for your program to run. Can you scale up 1000x, or 1000000x? If it takes very long to get the result, how do you think you can improve?

**Comment by kaiwenxu94** [comment]
@hupili I wonder if buying a 16G memory-chip helps. But I think we can improve the programming. Here is my idea:
Instead of calculating the break-even point by adding only 1 to the 'subscribers' parameter each time in a loop, we can scale up the step width, say, adding 10000 each time in the loop:
`subscribers=subscribers+10000`
Once the net income becomes greater than 0, the loop breaks. Then let the 'subscribers' parameter minus 1 every time in a loop. Once the net income becomes negative, the loop breaks.
Below are the codes that I write for the further challenge. You can check the results [here](http://nbviewer.jupyter.org/github/kaiwenxu94/hkbu-big-data-exercises-and-projects/blob/master/python%20exercises/week3/further%20challenge%20to%20calculate%20the%20break-even%20point-checkpoint.ipynb):
```
Fixed_Cost = 3000000
Content_Cost = 7000000
member_ff = 15
convert_rate = 0.1
ad_revenue_each_person = 1
subscribers=0
net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost
if net_income==0:
    print(subscribers)
else:
    while subscribers>=0:
        subscribers=subscribers+10000
        if subscribers<50000:
            net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost
        else:
            net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost-0.1*(subscribers-50000)
        if net_income>=0:
            break

while subscribers>=0:
    subscribers=subscribers-1
    if subscribers<50000:
        net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost
    else:
        net_income=0.1*subscribers*member_ff+ad_revenue_each_person*subscribers-Fixed_Cost-Content_Cost-0.1*(subscribers-50000)
        if net_income<0:
            break

subscribers=subscribers+1
print(subscribers)
```

**Comment by hupili** [comment]
Excellent! You are touching the door of "algorithm" now.

Can you put the "basic solution" and "optimised solution" in one notebook and use `%%time` to measure their efficiency given same scale of parameters? 

You can refer to this example: https://github.com/hupili/python-for-data-and-media-communication/blob/master/jupyter-notebook/timeit.ipynb

**Comment by FLYSTEPHEN** [comment]
I think @kaiwenxu94 's method is really brilliant.Based on his practice, I figure out a more automatic and efficient way. Generally, it is +100000 circularly and then -10000 in the same way until +/-1:
```bash
def net_income(visitor):
    if visitor<=basic_visitor:
        major_cost=fixed_cost
    else:
        major_cost=fixed_cost+(visitor-basic_visitor)*cloud_sever_fee
    
    revenue=visitor*ad_sponsorship+visitor*subscription_fee*convert_rate

    net_income=revenue-major_cost
    return net_income

content_cost=7000000
other_cost=300000
infrastructure_cost=50000000
cloud_sever_fee=0.001
subscription_fee=15
convert_rate=0.1
ad_sponsorship=0.8
basic_visitor=50000
fixed_cost=content_cost+other_cost+infrastructure_cost

%%time

i=0
e=len(str(fixed_cost))-1                #estimated scale of addend used firstly
f=int(e%2!=0)                           #make sure the first addend’s sign is +, since we use a (-1)**n to control +/- later
while e>=0:                             #end loop until 10**e=1
    while net_income(i)*(-1)**(e+f)<0:  #try to get a number bigger/smaller(depending on how many rounds) than the point
        #print(i)                       #memo of how f works: when e is odd number, f become 1, so the 1st e is always even number
        i=i+10**e*(-1)**(e+f)           #use a (-1)**n to control +/-; use f=int(e%2!=0) to make sure the first addend‘s sign is +
    e=e-1                               #promote precision and plus/minus again 
if net_income(i)<0:                     #if the loop ends with minus, we should add it back above 0
    i=i+1
    #print(i)
print('visitor=%s is the break even point'%i)
```
However, as @hupili said, using bisection method(二分法) will be even more faster! Here I skip the The basic function and constants:
```bash
i=0
e=len(str(fixed_cost))-1        #estimated scale of addend used firstly
g=10**e
while net_income(i)<0:          #firstly find a section (i0，i1) containing the break even point
    i=i+g
    #print(i)
i0=i-g
i1=i
while i1-i0>2:                  #avoid the endless loop when i1-i0=2, since there is i1=middle+1 in bisection
    middle=(i0+i1)//2
    if net_income(middle)<0:
        i0=middle               #no need for i0=middle-1 since fractional parts have been rounded down by '//'
    elif net_income(middle)>=0:
        i1=middle+1             #let i1=middle+1 so that if middle<x<middle+1 when net_income(x)=0, the x won't be skipped
    #print(i0,i1)
if net_income(i1-1)>=0:         #the point could be in (i1-1,i1) or (i1-2,i1-1)
    i1=i1-1
    #print(i1)
print('visitor=%s is the break even point'% i1)
```
I'm not sure whether they are correct, please kindly give me your advise!
I also launched a %%time test. The times are not stable, but still have reference value. please check [here](https://github.com/FLYSTEPHEN/Chapter-2-time-/blob/master/ex2-4-cal_break_even_point_directly(%25%25time).ipynb) if you want.

**Comment by hupili** [comment]
@FLYSTEPHEN very good try! 

For the “time not stable” issue, I guess it is because the execution is too fast. In this way, execution overhead weighs most. You may want to wrap your solution logics into one function and repeat that function to get a more stable estimation —— this is statistics —— larger repetition reduces variance.

For correctness, you can simply verify the output of your new algorithm against basic solution.

**Comment by FLYSTEPHEN** [comment]
I have updated the [time test](https://github.com/FLYSTEPHEN/Chapter-2-time-/blob/master/ex2-4-cal_break_even_point_directly(%25%25time).ipynb) by repeating the functions for 100000 times. The gap becomes distinct! Thank you for your advice @hupili .

**Comment by kaiwenxu94** [comment]
@FLYSTEPHEN Thank you! I also learned a lot from your codes!

**Comment by hupili** [comment]
@FLYSTEPHEN , @kaiwenxu94 , you are ahead of the crowed and clearly possess a potential to further develop algorithmic thinking. You can try [leetcode](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/leetcode.md) and discuss in our #leetcode Slack channel. I'm closing this issue now.
