### ISSUE TITLE
question about array

### ISSUE THREAD

**Issue by coolxu8888** [hupili/python-for-data-and-media-communication-gitbook#37]
![image](https://user-images.githubusercontent.com/42830310/45593877-612e0500-b9c2-11e8-932d-b623d862355a.png)
In the image, why is the highlight part '1,2,4' as a result of print? How come the result?
And I'm not quite understand 'Similarly, the first number is to index elements in this array, the second number is to index the sub-elements in each elements', could anyone help me out?

**Comment by iiiJenny** [comment]
@coolxu8888 
![image](https://user-images.githubusercontent.com/42435100/45594590-29c65500-b9d0-11e8-88b1-bc53d67518a4.png)
* you can image it as a matrix with 2 rows and 3 columns, and the index of the fist number ' 1 ' is [0, 0] , which means in the first row & first column (The index of first element is 0, in other words, row index is 0, column index is 0) .  In a similar way, ' 2 ' means in the first row& the second column ( b[0, 1] ),  ' 4 ' means in the second row& the first column ( b[0, 1] ).

![image](https://user-images.githubusercontent.com/42435100/45594704-adcd0c80-b9d1-11e8-8df9-aa21a1eb91ab.png)
* the first number ' 2 ' means there are 2  ranks, and the second number ' 3 ' means in each rank, there are 3 elements.

**Comment by coolxu8888** [comment]
Got it! Thanks!
