### ISSUE TITLE
Chapter 3 Working Thread - Python for anything: condition, loop, function, class

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#4]

**Comment by hupili** [comment]
@ChicoXYC one major feedback is to use Python script, instead of Python shell (interpreter), in chapter 3. You can see there are a lot of indentations when handling if/for/while/def/class. It is hard to type in Python shell. Also, readers find it hard to copy and paste for their own use. 

Note how we evolve the tool-chain:

* ch0/ ch1 — just play around with GitHub and Python
* ch2 — play basic arithmetic and library in Python shell — interactive; but without indentation — good for quickly testing an idea; but not conveniet to write larger project
* ch3 — play `.py` script; one can use `-i` option to enter interactive shell after this script (see how I revised this part of ch1). — This ways is more convenient to write big chunks of codes.
* ch4 — Jupyter notebook! We base all our work on this in the future weeks.

**Comment by ChicoXYC** [comment]
@hupili I noticed that and wrote a note in the control flow chapter to remind them to use the script mode, and change the code structure for better copying and pasting.

**Comment by hupili** [comment]
* [ ] https://github.com/hupili/python-for-data-and-media-communication-gitbook/commit/407caee19590c63ff0249d640d3fe506aa5c695f  -- I modified some part as examples. Please proceed with the rest of the document (and other document if any).

**Comment by hupili** [comment]
@ChicoXYC some comments in [last commit](https://github.com/hupili/python-for-data-and-media-communication-gitbook/commit/93a4f47ca64baf45e9c9422dd6792cc90a0bca76) needs to be further addressed.

Another thing is to solve and scan the following type of non-printable characters problem.

<img width="431" alt="screen shot 2018-08-26 at 7 24 17 pm" src="https://user-images.githubusercontent.com/1227160/44627758-da0ee380-a965-11e8-8404-81970e2f2488.png">

The remaining are minor revisions so I will release soon. Please keep revising and notify the thread when done.
