### ISSUE TITLE
CH06 Feedbacks

### ISSUE THREAD

**Issue by SerenaQYHuang** [hupili/python-for-data-and-media-communication-gitbook#42]
```
%curl https://nghttp2.org/httpbin/user-agent
{"user-agent":"curl/7.54.0"}
```
For this piece of coded, the output shows:

![image](https://user-images.githubusercontent.com/41979788/45827494-1ea15b00-bd29-11e8-8feb-bc120f7d9a46.png)

It seems that the magic function doesn't work here

**Comment by hupili** [comment]
that is for Terminal

In notebook, please prefix with ! instead of %
