### ISSUE TITLE
Chapter 0 - fork, modify, PR

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#43]
https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-00.md#the-workflow-fork-repo-modify-code-and-send-pull-request

@ChicoXYC you can use the recent update to the code repo as an example.

After adding back this TODO, I'll announce the further challenges/ exercises in week 00

**Comment by ChicoXYC** [comment]
Update
d5efce6 & e1b0c35

**Comment by hupili** [comment]
@ChicoXYC Let's try to make a complete example using the current book repo. (the last screenshot about Pull Request at present is on the code repo).

**Comment by hupili** [comment]
@ChicoXYC you have direct write permission of this repo, so you can make the "artificial example" yourself. Just create a PR, send and merge all by yourself.

After the revision of this section, we'll invite some helpers to test the workflow by contributing certain content.

**Comment by ChicoXYC** [comment]
update! ef55569
