### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by lullabymia** [hupili/python-for-data-and-media-communication-gitbook#47]
# Troubleshooting
I wrote this programme to allocate cases for each five students. But it seems something goes wrong with the index on the line " print(list2[s])" and "print(list1[c:c+5])". How can I give value 0 to s and c, also change the values each time.

student_list =[
18421111,
18421112,
18421113,
18421114,
18421115,
18421116,
18421117,
18421118,
18421119,
18421120,
18421121,
18421122,
18421123,
18421124,
18421125,
18421126,
18421127,
18421128,
18421129,
18421130,
18421131,
18421132,
18421133,
18421134,
18421135,
18421136,
18421137,
18421138,
18421139,
18421140,
18421141,
18421142,
18421143,
18421144,
18421145,
18421146,
18421147,
18421148,
18421149,
18421150,
18421151,
18421152,
18421153,
18421154,
18421155,
18421156,
18421157,
18421158,
18421159,
18421160,
]
case_list =[
'case1 - build a calculator to evaluate your business model',
'case2 - build a automatic earthquake robot to broadcast the new earthquake',
'case3 - evaluate social media performance of a luxury brand',
'case4 - study movie blockbuster 'Dying to Survive'',
'case5 - invest your money like the Internet giant, Tencent',
'case6 - where are the 200,000 inferior vaccines flowing?',
'case7 - study classics, Who control the discourse power in 'Dream of the Red Chamber'',
'case8 - research about Didi-driver crimes in China',
'case9 - 'Me too' analysis',
'case10 - what is hip-hop in china?'
]

import random
random.shuffle(student_list)
list1=student_list
print(list1)
random.shuffle(case_list)
list2=case_list
print(list2)

s=0
c=0
for s in student_list:

print(list2[s])
s=s+1
for c in case_list:
    
    print(list1[c:c+5])
    c=c+5

**Comment by ChicoXYC** [comment]
@lullabymia 

you are right till this loop `for s in student_list:`

Translate this into natural language, you want to create a loop list of students. In this case, we can easily know its 5 each. Therefore it should be grouped like this [0:5] ,[5,10],[10,15]....[45,50]. I guess you've already found what's happening here. It increases with 5 intervals, therefore we can use `[5*i:5*i+5]` to replace all the groups. The only thing we need to handle now is `i`. And `i` is exactly the number of the group, or the length of cases. Therefore we can write the following loop to form different groups.

```python
for i in range(0,len(case_list)):
    print('Student ID: {0}'.format(list1[i*5:i*5+5]))
    print('Assigned case:{0}'.format(list2[i]))
    print('----------------------------------') 
```
**Note:** use `string.format` to form the output we want.

The output will be like this:

```text
Student ID: [18421157, 18421142, 18421114, 18421139, 18421156]
Assigned case:case1 - build a calculator to evaluate your business model
----------------------------------
Student ID: [18421117, 18421147, 18421134, 18421133, 18421113]
Assigned case:case6 - where are the 200,000 inferior vaccines flowing?
----------------------------------
Student ID: [18421122, 18421128, 18421148, 18421121, 18421154]
Assigned case:case10 - what is hip-hop in China?
----------------------------------
Student ID: [18421115, 18421124, 18421126, 18421112, 18421152]
Assigned case:case7 - study classics, Who control the discourse power in 'Dream of the Red Chamber'
----------------------------------
Student ID: [18421130, 18421127, 18421129, 18421153, 18421125]
Assigned case:case8 - research about Didi-driver crimes in China
----------------------------------
Student ID: [18421116, 18421132, 18421160, 18421159, 18421151]
Assigned case:case5 - invest your money like the Internet giant, Tencent
----------------------------------
Student ID: [18421146, 18421111, 18421118, 18421145, 18421120]
Assigned case:case3 - evaluate social media performance of a luxury brand
----------------------------------
Student ID: [18421137, 18421141, 18421158, 18421119, 18421135]
Assigned case:case9 - 'Me too' analysis
----------------------------------
Student ID: [18421136, 18421140, 18421150, 18421138, 18421123]
Assigned case:case4 - study movie blockbuster 'Dying to Survive'
----------------------------------
Student ID: [18421155, 18421143, 18421131, 18421149, 18421144]
Assigned case:case2 - build an automatic earthquake robot to broadcast the new earthquake
----------------------------------
```

In reality, the case is usually more complicated, what if I want to divide in 17goups with total 1000 students, how should I write the loop and how to assign the extra member? in which group? I remembered @ConnorLi96 has done this practice, maybe you can explain or talk with her more?

**Comment by ConnorLi96** [comment]
@lullabymia If you want to divide in 17goups with total 1000 students, how to write the loop and how to assign the extra member? This question is related with a condition that the number of students cannot be divided by the number of cases, which looks so complicated. But do not feel scared. Actually, when we face some complex problems, there is a thinking strategy 'Divide and conquer'. Divide your problem into two parts and conquer them separately. Here is a [example,](https://github.com/ConnorLi96/python-notebook/blob/master/Divide%20and%20conquer%20分而治之.ipynb) I sincerely advice you check it after you thinking independently, which can help you learn more.

**Comment by ChicoXYC** [comment]
@ConnorLi96 excellent!!! @lullabymia if you still have questions, just leave your comment

**Comment by hupili** [comment]
@ConnorLi96 , please see if you can further appreciate this:

https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/computational-thinking.md#recursion-implementation

**Comment by ConnorLi96** [comment]
@hupili Amazing!! This question once puzzled me for 8 hours, you just write 3 lines to handle it. This code gave me a lot of inspiration. Thank you so much for your sharing!
