### ISSUE TITLE
issues about installing jupyter in CVA517

### ISSUE THREAD

**Issue by ChicoXYC** [hupili/python-for-data-and-media-communication-gitbook#48]
[Here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-jupyter.md) are the instruction of how to install jupyter generally, we typing following command to create virtual environment then install all dependencies and modules. But in lab, there are some problem:
 
```
pyvenv venv
source venv/bin/activate
pip3 install jupyter
```

<img width="697" alt="screen shot 2018-10-01 at 6 28 09 pm" src="https://user-images.githubusercontent.com/37010763/46284220-92edc100-c5a9-11e8-9e45-124a7e12868d.png">

You will get the error of upgrade your `pip` version during install jupyter, just copy the command.

```
pip install --upgrade pip
```

Then, install jupyter, open the jupyter notebook

```
pip3 install jupyter
jupyter notebook
```
<img width="1271" alt="screen shot 2018-10-01 at 6 29 54 pm" src="https://user-images.githubusercontent.com/37010763/46284315-ee1fb380-c5a9-11e8-85b8-f0a781872dc8.png">

then you will encounter another problem, whenever you execute what, it shows its in running and there is a sign saying that `kernel starting, please wait...` The reason can be found in the terminal
that when you install jupyter, there is an red line saying:
```
ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
```
<img width="697" alt="screen shot 2018-10-01 at 6 29 06 pm" src="https://user-images.githubusercontent.com/37010763/46284519-b7966880-c5aa-11e8-958c-985ba2fdffdd.png">

In oder to solve this, there is two solutions which can be found in [jupyter_kernel issue#158](https://github.com/jupyter/jupyter_console/issues/158)

solution 1: `pip install 'ipykernel<5.0.0' `

solution 2: first downgraded ipython `pip install -U ipython==6.5.0`, then prompt-tookit `pip install -U prompt-toolkit==1.0.15`

Finally, open jupyter notebook, type something to test, it should work now!
<img width="1278" alt="screen shot 2018-10-01 at 6 33 56 pm" src="https://user-images.githubusercontent.com/37010763/46284845-e82ad200-c5ab-11e8-8968-6aa57d2ccc0d.png">

**Comment by hupili** [comment]
```shell
pyvenv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade pip3
pip3 install ipython ==6.5.0
pip3 install prompt-toolkit ==1.0.15
pip3 install jupyter
```

@ChicoXYC , based on your notes, does the above work in our lab in a copy-and-paste manner?

**Comment by ChicoXYC** [comment]
The following will work
```
pyvenv venv
source venv/bin/activate
pip install --upgrade pip
pip3 install 'ipython ==6.5.0'
pip3 install 'prompt-toolkit ==1.0.15'
pip3 install jupyter
```

**Comment by hupili** [comment]
@ChicoXYC , if this is merged into notes/ FAQ, you can leave a message and a link here. Then we can close the issue.

**Comment by ChicoXYC** [comment]
Merged into FAQs. Please refer here: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-jupyter.md#set-jupyter-environment-in-cva517
