### ISSUE TITLE
A question about the codes to extract article url in week5 - [improve: list slicing]

### ISSUE THREAD

**Issue by kaiwenxu94** [hupili/python-for-data-and-media-communication-gitbook#49]
For the example in week5 which extracts all article urls in http://initiumlab.com, all the tags including the article urls have been collected like below
![image](https://user-images.githubusercontent.com/42831899/46424907-f83ddf80-c76c-11e8-82ea-7b64b22804a7.png)

Next, we need to get the strings after 'href' (e.g.'href="../blog/20170113-Sharing-With-Friends-Versus-Strangers/"'), and the codes are as below:
```
for my_url in my_urls:
    url ='{0}{1}'.format('http://initiumlab.com',my_url['href'][2:]) #format urls
        #print(url)
    article_urls.append(url)
article_urls

```
However, I do not quite understand what `my_url['href'][2:]` means here. 'my_url['href']' seems to be a function of finding the  value through the corresponding key in a dictionary, but 'my_url' is a list element.  [2:] seems to be a function of extracting part of words in string. I feel a little bit confused.

**Comment by ConnorLi96** [comment]
@kaiwenxu94 Actually, [2:] is not a function, just a "list slicing". You can try to change the number whatever you want, and observe what happen. Such as [1:15], [2:10],[3:6],etc. Below is a detailed explanation about "list slicing", you can check it. Hope you find my responses useful.
[https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-03.md#common-features-of-list](url)

**Comment by hupili** [comment]
@ChicoXYC , list slicing is worth a subsection, just like the `in` operator. I have given more demo, e.g. `a[-1]`, during the class. Those fundamental could be useful in the long run. [Here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/leetcode.md#list) is a leetcode question that list slicding could be very useful.

**Comment by ChicoXYC** [comment]
Update list slicing. Please refer to our notes: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/4910697fc6f5b32701adf1df6a593dbec4581506/notes-week-03.md#list-slicing
