### ISSUE TITLE
Chapter 4 Working Thread - API/ JSON/ CSV

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#5]

**Comment by hupili** [comment]
@ChicoXYC , in case you didn't notice, there are some TODO comments in the file body.

* [ ] Address "TODO" comments in the file body.

**Comment by hupili** [comment]
You can ask for pilot test while polishing up. We now have some committed helpers. They are learning at different pace. For those who finished ch3's challenge, they can join ch4 at this pilot stage. After we finish polishing in this thread, the rest can join. Then we release to the whole precamp.

**Comment by zhangjingwei0512** [comment]
Hello，teacher and student.When doing my exercises,I found something wrong and don't know the reason.Hopefully to get answers from you! Thanks!
my code is:

![1](https://user-images.githubusercontent.com/42828228/44955634-118f0a00-aee9-11e8-8695-5aeaa4d40f04.PNG)

However,the python shows:
![2](https://user-images.githubusercontent.com/42828228/44955637-426f3f00-aee9-11e8-8cb7-450c07d73f54.PNG)

I suppose there is something wrong to transform into json file,but how to solve it?
Thanks!

**Comment by hupili** [comment]
@zhangjingwei0512 , you're right. The error means no JSON can be parsed. Can you check the output of `response.text`? You need first to make sure the response is a valid JSON object, before using `.json()` function to parse it into Python's internal data structure.

**Comment by hupili** [comment]
@zhangjingwei0512 I just checked the URL you are using ( [exampe](https://movie.douban.com/explore#!type=movie&tag=sci) ). It is not intended to parse as JSON. It returns an HTML page. You can use week-05's knowledge to handle the semi-structured scraping.

For week-04, we rely on HTTP API that returns JSON object. Example APIs from douban are given here: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-04.md#douban-api

**Comment by hupili** [comment]
An additional note: you need to check the `response` object before doing further processing. `response.code`, `response.text`, `response.content` are useful.

**Comment by hupili** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by zhangjingwei0512** [comment]
@hupili Thanks for your answer,however,I still have one further question about this.
![3](https://user-images.githubusercontent.com/42828228/45037169-f6f79500-b090-11e8-8dc6-98302540df5b.PNG)

This is the example you show us,and I wonder why it can generate JSON files successfully,
I noticed that if using api_url instead of url,I mean changing the code into response=requests.get(api_url),
the python shows the error like the picture above.

So,could you tell us the difference between them,is it affected by the parameters?

Also,What is method to know the parameters that make up API.In this case,the parameters like the starttime,minlatitude is given.If we change an example,how to set the parameters?
Thanks!

**Comment by hupili** [comment]
Reopened. I think we need to elaborate week-04 notes. @ChicoXYC please help first and pass to me if unsolved. I just re-read the codes and find following improvements are needed:

* [ ] Use string templating instead of string concatenation -- remember best practice -- or it is hard to change their first impression later on.
* [ ] Demo `count` first and then demo `query`. One principle of the open book is to find the "shortest path" to result. Once the first result is given, we can quickly pass through alternatives/ extended exercises.

**Comment by ChicoXYC** [comment]
@zhangjingwei0512 
Firstly, different organizations and websites have their own rules for using API. 

For this earthquake API, you cannot just request all data from this original API link(api_url), they just give you a hint that you should format your API based on this original API. Therefore you need to specify which region, what period of time of data you want. 

It's like declare what content/data you want to request. Then you can just pass those parameters following the original API link to request those data, you can click the API link see their examples to learn more. https://earthquake.usgs.gov/fdsnws/event/1/

**Comment by ChicoXYC** [comment]
@hupili update
- seperate two request method
- give more explanation of API 
- give more explanation of extract data we want
- Change API formating
