### ISSUE TITLE
Broken paths after moving the images

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#50]
one example:

https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-python-twitter.md

<img width="574" alt="screen shot 2018-10-04 at 12 35 40 pm" src="https://user-images.githubusercontent.com/1227160/46453073-040fbd00-c7d2-11e8-830c-f32a3878eb71.png">

**Comment by ChicoXYC** [comment]
@hupili  Update. Also checked out and fixed other files.
