### ISSUE TITLE
comments on Chapter7 - [improve: better narrative/ elaboration]

### ISSUE THREAD

**Issue by rippleYJH** [hupili/python-for-data-and-media-communication-gitbook#53]
1. If we do not define the bins when using hist() function, it seems I can not get a distribution image. So do we need to always define the bins by ourselves?
![image](https://user-images.githubusercontent.com/42017792/46645585-2467bf00-cbb8-11e8-97d6-b578b540ee12.png)

2. Do we need to define the key and value in mapping function? If we have vast sum of data, how could we be more convenient to clean the data?

3. I try to apply "descending=False" (it supposed to be sorting by ascending, but there is no keyword argument defined. So in sort function, we can only apply 'ascending' by using True/False right?)

4. I dont know why I cannot get a csv.file after using the to_csv format, and why should I input 'index' here? 

Thanks a lot!

**Comment by rippleYJH** [comment]
Like this:
![image](https://user-images.githubusercontent.com/42017792/46646887-706a3200-cbbf-11e8-921c-95e9a6445a69.png)

**Comment by ConnorLi96** [comment]
@rippleYJH If  I don't define the bins, I also can get image, but need some time and the python will be launched automatically. Maybe you can try again, or try other elements, like 'price' or  'style'.

**Comment by rippleYJH** [comment]
Right! I refreshed three times and finally got the image, maybe due to the slow processing speed. Good to know and thanks for your advice! @ConnorLi96

**Comment by hupili** [comment]
@rippleYJH can you also try to place the following in the beginning of the notebook?

```python
%matplotlib inline
import matplotlib
```

This instruction allows Python to plot onto Jupyter's web page directly (a.k.a. inline). It was default behaviour in some versions but the recent update of Jupyter changed this behaviour. Putting this in the front cell may help to alleviate the problem.

**Comment by rippleYJH** [comment]
Yes it actually works! Maybe we can also have a reminder in the openbook. thanks :)

**Comment by hupili** [comment]
@ChicoXYC , @ConnorLi96  token is on you now. The other questions should be straight once you are familiar with the functions.

**Comment by hupili** [comment]
@ChicoXYC , for the clarification questions, please try to see how to improve our presentation of the book.

**Comment by ChicoXYC** [comment]
merged into notes. https://github.com/hupili/python-for-data-and-media-communication-gitbook/commit/cff6d7faac0a285447bcf2754db1a0f6ec5380d4
