### ISSUE TITLE
Ch6 Feedbacks - [improve: partial link & scroll]

### ISSUE THREAD

**Issue by FLYSTEPHEN** [hupili/python-for-data-and-media-communication-gitbook#57]
- In this section [#advanced-all-pages](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-06.md#advanced-all-pages)
the second line from the bottom `df = pd.DataFrame(articles)` may should be `df = pd.DataFrame(all_page_articles)`, otherwise the variable `articles` cannot be found.

- In this section [#navigating](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-06.md#navigating)
The introduction words ’You can doing a lot of interactive things with the webpage... ‘ should be 'You can do ...'
The line from the bottom `link = browser.find_element_by_link_text('GitHub - hupili/python-for-data-and-media-communication-gitbook')` could use `find_element_by_partial_link_text` instead, in case the text of link cannot be displayed completely on some small screens like mine:(

**Comment by hupili** [comment]
👍   partial link is a good point!

It is better to revise the script so that we don't rely on texts. There is a potential loophole about text -- text shown differently with different language system. It is better to find by id or by class

**Comment by ChicoXYC** [comment]
@FLYSTEPHEN thanks a lot. Yes, find elements by partial_link is easier, but if there are links that have similar link text, it will be a little bit confusing. But generally, its good.

**Comment by hupili** [comment]
@ChicoXYC , here are two TODO items:

- [ ] Change `find_element_by_link_text` to other more stable solutions
- [ ] Change `execute_script('window.scrollTo` to the better practice that I just demoed in #65

**Comment by ChicoXYC** [comment]
@our notes already include `find_elements_by_partial_link` with a example. I will check the other one.

**Comment by hupili** [comment]
> There is a potential loophole about text -- text shown differently with different language system. **It is better to find by id or by class**

@ChicoXYC , I mean: put `find_elements_by_partial_link` as alternative; and use id or class as primary solution. The key point here is not "partial". It is "by text". We should not find by text, if `tag#id.class` works. Unless finding by text is the only solution, or other methods cause big inconvenience, we can use it as primary solution.

**Comment by ChicoXYC** [comment]
@hupili in the google search navigating, there is only tag with no other attributes that can help to specifically locate the elements we want. I think in this case, the partial link is helpful. Students also need to learn other alternative solutions if there is no class name, id...

**Comment by hupili** [comment]
I will do the following as primary practice:

- Search by class `g` to locate the search results.
- Use list slicing to get the first entry 
- From the first entry (a div), search by tag `a` to find the link

**Comment by ChicoXYC** [comment]
@hupili but if the result we want is between the results, like if there are 100 each page, and we have to find the location manually then use the list slicing to get the results, I think its a little bit more complicated compared with find elements by partial link.

**Comment by hupili** [comment]
Partial link can be alternative. it is seldom used when you scrape real data. In this case, you just happen to know which link you want to click. In real scraping, navigating list is more common.

**Comment by hupili** [comment]
I see from another thread that you used "scrollIntoView" to help someone solve the issue. This can also be added to the alternative area.

**Comment by ChicoXYC** [comment]
@hupili Okay

**Comment by ChicoXYC** [comment]
* merged into notes: Window scroll methods: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-06.md#scroll-down-certain-element
* merged into FAQs: Takeaways on `select_element_by_css_selector`: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-selenium.md#find-elements-by-css-selector
