### ISSUE TITLE
The problem about assignment0

### ISSUE THREAD

**Issue by efncij** [hupili/python-for-data-and-media-communication-gitbook#58]
<img width="459" alt="_20181020020543" src="https://user-images.githubusercontent.com/42829112/47235812-bf5c6680-d40c-11e8-95da-1885a736aa0f.png">

I wrote this but it can not be run. Can someone tell me how to amend it? Thanks!

**Comment by efncij** [comment]
I ran it, but there is no reflection.

**Comment by hupili** [comment]
from what I can see, you only defined the functions via `def` without executing them. In this way nothing will be trigger (the function body will note be actually executed unless you call them like`lineprocess()` in aonther cell).

**Comment by ChicoXYC** [comment]
@efncij have you solved the problem?
