### ISSUE TITLE
Question about assignment0

### ISSUE THREAD

**Issue by yaonuan1995** [hupili/python-for-data-and-media-communication-gitbook#59]
f = open("trade-wars-news1.txt","r+")
content1 = f.read()
f.close()
g = open("trade-wars-news2.txt","r+")
content2 = g.read()
g.close()
h = open("trade-wars-news3.txt","r+")
content3 = h.read()
h.close()
i = open("trade-wars-news4.txt","r+")
content4 = i.read()
i.close()
j = open("trade-wars-news5.txt","r+")
content5 = j.read()
j.close()

A = str.split(content1)
B = str.split(content2)
C = str.split(content3)
D = str.split(content4)
E = str.split(content5)

wordlist = list(A)+list(B)+list(C)+list(D)+list(E)

wordcount = {}
for word in wordlist:
    if word in wordcount:
        wordcount[word] += 1
    else:
        wordcount[word] = 1

wordscount = dict.fromkeys(wordlist,wordcount)

a = sorted(wordscount,key=wordscount.get,reverse=True)

![Uploading 屏幕快照 2018-10-22 上午9.42.59.png…]()

**I don't know why I could not run it, the error type is in the last line,  "not supported between instances of 'dict' and 'dict'".**

**Comment by hupili** [comment]
@yaonuan1995 , the screenshot is lost, maybe due to the service interruption of GitHub this afternoon. Also, you may want to reformat the text into code block, or else the indentation is lost. See [this section](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-00.md#code-block--syntax-highlighting)

**Comment by yaonuan1995** [comment]
> @yaonuan1995
> I think the following two lines have some problem because you 've already gotten the `wordcount` dict, so the first line is meaningless.
> 
> ```python
> wordscount = dict.fromkeys(wordlist,wordcount)
> a = sorted(wordscount,key=wordscount.get,reverse=True)
> ```
> 
> you can get the sorted list and the top 15 by the following command
> 
> ```python
> word_sorted = sorted(wordcount.items(),key=lambda d: d[1],reverse=True)
> top15 = word_sorted[:15]
> top15
> ```
> 
> Now, you can try to do a further excercise:
> 
> 1. Build your own stopwords list, removing some stopwords we don't want in the wordlist.
> 
> ```python
> stopwords = ['the','of','to','is','in','that','as','on','with','a','and'....]
> def remove_stopwords(words):
>     processed_word_list = []
>     for word in wordlist:
>         if word ...:
>             processed_word_list....
>     return ...
> 
> ... = remove_stopwords(wordlist)
> ```
> 
> 1. further organise your code for future reuse? you can refer to assignment 0 [guideline](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/assignments.md#bonus-discussion-or-demo)

Thanks!!!
