### ISSUE TITLE
Change file naming convention

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#6]
Here is the file naming convention:

https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/guide-for-contributor.md#file-naming-convention

Please do a quick scan in the `assets` folder and change the file names and their corresponding references in the markdown files.

**Comment by hupili** [comment]
@ChicoXYC please leave a message once done for all the weeks. As discussed, you can subfolder those files first to make the outlook clean.

**Comment by hupili** [comment]
@ChicoXYC , after moving the image files, please change the corresponding path in the markdown file. https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-07.md  . The project is under development but please make sure it reads in its best status no matter when others check it out.

**Comment by ChicoXYC** [comment]
@hupili  finish tidying of week 5-7
