### ISSUE TITLE
CH07 Feedback

### ISSUE THREAD

**Issue by SerenaQYHuang** [hupili/python-for-data-and-media-communication-gitbook#61]
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?:07

## I've got an issue with the following piece of code:
```
df.sort_values(by='likes',ascending=False)
```
 ### First, 'df' is not defined. I considered the possibility of a typo, and I tried inputting like:
```
dict_series.sort_values(by='likes',ascending = False)
```

**Comment by ChicoXYC** [comment]
@SerenaQYHuang 
1. the first one is just an example of how to sort values of dataframe, its similar like sort values of series , its just `a syntax example`.
2. replace the csv url ink to `raw link` should be fine. Update in notes. 
url="https://raw.githubusercontent.com/hupili/python-for-data-and-media-communication/master/scraper-examples/open_rice/openrice_sample.csv"

Thanks  a lot!

**Comment by SerenaQYHuang** [comment]
> @SerenaQYHuang
> 
> 1. the first one is just an example of how to sort values of dataframe, its similar like sort values of series , its just `a syntax example`.
> 2. replace the csv url ink to `raw link` should be fine. Update in notes.
>    url="https://raw.githubusercontent.com/hupili/python-for-data-and-media-communication/master/scraper-examples/open_rice/openrice_sample.csv"
> 
> Thanks a lot!

Problems solved. Thank you so much Chico!

**Comment by ChicoXYC** [comment]
@SerenaQYHuang thanks a lot. update

**Comment by hupili** [comment]
Thanks @SerenaQYHuang ! Detailed orientation is highly appreciated.

Please help to proof-read when new notes come out. We need to make sure at least others have no problem following the notes in a verbatim way. Easy comprehension is the next layer of goal.

**Comment by ChicoXYC** [comment]
@SerenaQYHuang Thanks again. Closed
