### ISSUE TITLE
A question about Booking scraping

### ISSUE THREAD

**Issue by Shinonomee** [hupili/python-for-data-and-media-communication-gitbook#62]
from selenium import webdriver

browser = webdriver.Chrome()
browser.get('https://www.booking.com/searchresults.zh-cn.html?aid=378266&label=booking-name-IquAp*EbiLS6jPVl_he8yQS267778093594%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap1t1%3Aneg%3Afi%3Atikwd-65526620%3Alp9061634%3Ali%3Adec%3Adm&sid=75a6a10fd83d509dc44f2bc75e94dc31&checkin_month=9&checkin_monthday=12&checkin_year=2019&checkout_month=9&checkout_monthday=13&checkout_year=2019&city=-240905&class_interval=1&dest_id=-240905&dest_type=city&from_sf=1&group_adults=2&group_children=0&label_click=undef&no_rooms=1&raw_dest_type=city&room1=A%2CA&sb_price_type=total&shw_aparth=1&slp_r_match=0&src=searchresults&srpvid=342a6023a36e0036&ss=%E5%A4%A7%E9%98%AA&ssb=empty&ssne=%E5%A4%A7%E9%98%AA&ssne_untouched=%E5%A4%A7%E9%98%AA&nflt=di%3D7322%3Bpri%3D2%3B&rsf=pri-2&lsf=pri%7C2%7C136')

hotels = []
for session in browser.find_elements_by_css_selector('#hotellist_inner.hotellist sr_double_search'):
    hotel = {}
    n = session.find_element_by_css_selector('span.sr-hotel__name')
    hotel['name'] = n.text
    hotel['score'] = session.find_element_by_css_selector('div.bui-review-score__badge').text
    hotels.append(hotel)
hotels

**I  use the selenium to scrape the information on Booking, but the output is [ ].  I got no error message , just the empty [ ]. Could someone find is there anything wrong with it? Thank you!**

**Comment by ChicoXYC** [comment]
@Shinonomee I think its mainly because you write wrong css selector
<img width="504" alt="screen shot 2018-11-01 at 12 31 38 pm" src="https://user-images.githubusercontent.com/37010763/47832776-55f83280-ddd2-11e8-9ba2-40ba0de2dc31.png">

from outter to inner, upper to lower
the line you wrote is wrong with level`('#hotellist_inner.hotellist sr_double_search').


@hupili there is a problem about css selector. If I write the css with the way you taught me, the element cannot be found. But with xpath it works. And also if i wirte use the `css styles` in dev tools, it works too! So, whats wrong this the first solution？ Details please check out here:
https://nbviewer.jupyter.org/github/ChicoXYC/exercise/blob/master/css%20selector.ipynb

<img width="565" alt="screen shot 2018-11-01 at 12 40 54 pm" src="https://user-images.githubusercontent.com/37010763/47832998-7b397080-ddd3-11e8-96be-b37eaceeedfb.png">

**Comment by Shinonomee** [comment]
> @Shinonomee I think its mainly because you write wrong css selector
> <img alt="screen shot 2018-11-01 at 12 31 38 pm" width="504" src="https://user-images.githubusercontent.com/37010763/47832776-55f83280-ddd2-11e8-9ba2-40ba0de2dc31.png">
> 
> from outter to inner, upper to lower
> the line you wrote is wrong with level`('#hotellist_inner.hotellist sr_double_search').
> 
> @hupili there is a problem about css selector. If I write the css with the way you taught me, the element cannot be found. But with xpath it works. And also if i wirte use the `css styles` in dev tools, it works too! So, whats wrong this the first solution？ Details please check out here:
> https://nbviewer.jupyter.org/github/ChicoXYC/exercise/blob/master/css%20selector.ipynb
> 
> <img alt="screen shot 2018-11-01 at 12 40 54 pm" width="565" src="https://user-images.githubusercontent.com/37010763/47832998-7b397080-ddd3-11e8-96be-b37eaceeedfb.png">



> @Shinonomee I think its mainly because you write wrong css selector
> <img alt="screen shot 2018-11-01 at 12 31 38 pm" width="504" src="https://user-images.githubusercontent.com/37010763/47832776-55f83280-ddd2-11e8-9ba2-40ba0de2dc31.png">
> 
> from outter to inner, upper to lower
> the line you wrote is wrong with level`('#hotellist_inner.hotellist sr_double_search').
> 
> @hupili there is a problem about css selector. If I write the css with the way you taught me, the element cannot be found. But with xpath it works. And also if i wirte use the `css styles` in dev tools, it works too! So, whats wrong this the first solution？ Details please check out here:
> https://nbviewer.jupyter.org/github/ChicoXYC/exercise/blob/master/css%20selector.ipynb
> 
> <img alt="screen shot 2018-11-01 at 12 40 54 pm" width="565" src="https://user-images.githubusercontent.com/37010763/47832998-7b397080-ddd3-11e8-96be-b37eaceeedfb.png">

from selenium import webdriver

browser = webdriver.Chrome()
browser.get('https://www.booking.com/searchresults.zh-cn.html?aid=378266&label=booking-name-IquAp*EbiLS6jPVl_he8yQS267778093594%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap1t1%3Aneg%3Afi%3Atikwd-65526620%3Alp9061634%3Ali%3Adec%3Adm&sid=75a6a10fd83d509dc44f2bc75e94dc31&checkin_month=9&checkin_monthday=12&checkin_year=2019&checkout_month=9&checkout_monthday=13&checkout_year=2019&city=-240905&class_interval=1&dest_id=-240905&dest_type=city&from_sf=1&group_adults=2&group_children=0&label_click=undef&no_rooms=1&raw_dest_type=city&room1=A%2CA&sb_price_type=total&shw_aparth=1&slp_r_match=0&src=searchresults&srpvid=342a6023a36e0036&ss=%E5%A4%A7%E9%98%AA&ssb=empty&ssne=%E5%A4%A7%E9%98%AA&ssne_untouched=%E5%A4%A7%E9%98%AA&nflt=di%3D7322%3Bpri%3D2%3B&rsf=pri-2&lsf=pri%7C2%7C136')

hotels = []
for session in browser.find_elements_by_css_selector('#hotellist_inner.sr_item sr_item_new sr_item_default sr_property_block  sr_flex_layout'):
    hotel = {}
    n = session.find_element_by_css_selector('span.sr-hotel__name')
    hotel['name'] = n.text
    hotel['score'] = session.find_element_by_css_selector('div.bui-review-score__badge').text
    hotels.append(hotel)
hotels

**I modified it but the output is still the empty [ ]. And when I use css selector just to find elements under the id hotellist_inner, I find that it cannot find all the 25 hotels on this page. What's the reason? Thanks!**

**Comment by hupili** [comment]
`In[6] ~ In[18]` in [this notebook](https://github.com/hupili/python-for-data-and-media-communication/blob/314b2469290f28ed146b8d5c2e49be962e32e1d7/scraper-selenium/booking.com.ipynb) shows you how to get data from the booking.com page using CSS selector.

There are two points to note:

- When using `.className` notation, every class needs a prefix `.`: `.className1.className2.className3` (no blanks between those class names if they are used to attribute one element)
- The above screenshot that highlights two class names from "Styles" pane is a co-incidence. This pane shows all the styles that are activated for this element. Some styles are inherited from the parent/ ancestor element. You may not always get the current element of interest.

**Comment by ChicoXYC** [comment]
@ChicoXYC thanks a lot. It's much more clear now. @Shinonomee you can check out the above notebook for reference.

**Comment by Shinonomee** [comment]
Thank you!!!!

**Comment by ChicoXYC** [comment]
@hupili update in notebook 7be520e. Other students can check out for more.
