### ISSUE TITLE
A question about scraping

### ISSUE THREAD

**Issue by yaonuan1995** [hupili/python-for-data-and-media-communication-gitbook#63]
I want to scrap the data from New York Times(https://www.nytimes.com/section/world). But when I finished, I found that I can just scrap 59 entries. However, when I got to the bottom of the website, there is a "SHOW MORE" button and we can see more articles after clicking the button. How can I scrap more data?
<img width="809" alt="2018-11-02 10 10 16" src="https://user-images.githubusercontent.com/42726613/47890079-328fbf00-de88-11e8-9a74-b89b394fb6f0.png">

**Comment by SerenaQYHuang** [comment]
## Try the following steps:
### 1. Open the Chrome DevTools:

![image](https://user-images.githubusercontent.com/41979788/47892358-2f013580-de92-11e8-9e21-6de3b61b6abc.png)

### 2. Click the SHOW MORE button:

![image](https://user-images.githubusercontent.com/41979788/47892375-4a6c4080-de92-11e8-8278-2dab1b677b79.png)

### 3. Select the elements that appear and check their source codes

![image](https://user-images.githubusercontent.com/41979788/47892330-0f6a0d00-de92-11e8-8f0c-8e379317062a.png)

![image](https://user-images.githubusercontent.com/41979788/47892400-74bdfe00-de92-11e8-847c-c4f3b2c21e50.png)

### 4. Try scraping them targetedly

### Pls. feedback if it works (or does not work)

**Comment by yaonuan1995** [comment]
> ## Try the following steps:
> ### 1. Open the Chrome DevTools:
> ![image](https://user-images.githubusercontent.com/41979788/47892358-2f013580-de92-11e8-9e21-6de3b61b6abc.png)
> 
> ### 2. Click the SHOW MORE button:
> ![image](https://user-images.githubusercontent.com/41979788/47892375-4a6c4080-de92-11e8-8278-2dab1b677b79.png)
> 
> ### 3. Select the elements that appear and check their source codes
> ![image](https://user-images.githubusercontent.com/41979788/47892330-0f6a0d00-de92-11e8-8f0c-8e379317062a.png)
> 
> ![image](https://user-images.githubusercontent.com/41979788/47892400-74bdfe00-de92-11e8-847c-c4f3b2c21e50.png)
> 
> ### 4. Try scraping them targetedly
> ### Pls. feedback if it works (or does not work)

Sorry, it doesn't work...

**Comment by SerenaQYHuang** [comment]
## One possible solution is as follows. Quoted from [here](https://stackoverflow.com/questions/48160554/using-python-requests-to-simulate-clicking-a-show-more-button)  by [Ron Norris](https://stackoverflow.com/users/8093469/ron-norris)

> You'll have to select a different tool to press a button. One possible solution is Selenium, which can tell the browser to press the button. The following example clicks the show more button.
> 
> ```
> import time
> from selenium import webdriver
> from selenium.webdriver.chrome.options import Options
> 
> def executeTest():
>     global driver
>     driver.get('http://www.sciencedirect.com/science/article/pii/S2211926417300024')
>     time.sleep(7)
>     element = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/section/div/div[2]/article/div[2]/button')
>     element.click()
>     time.sleep(3)
> 
> def startWebDriver():
>     global driver
>     options = Options()
>     options.add_argument("--disable-infobars")
>     driver = webdriver.Chrome(chrome_options=options)
> 
> if __name__ == "__main__":
>     startWebDriver()
>     executeTest()
>     driver.quit()
> ```

**Comment by hupili** [comment]
@yaonuan1995 what is your current code and intermediate results? It helps to give the link to your current notebook, so we can start from where you got stuck.

**Comment by yaonuan1995** [comment]
> @yaonuan1995 what is your current code and intermediate results? It helps to give the link to your current notebook, so we can start from where you got stuck.
<img width="648" alt="2018-11-03 10 23 56" src="https://user-images.githubusercontent.com/42726613/47953378-c9a76480-dfb7-11e8-9cc9-80e5b731486e.png">
This is my notebook before.
I have tried the solution from TA, but I found some mistakes of my computer. When I install selenium, I could not put the chromedriver to "/urs/bin". So, I want to know if there is any other solution to click the SHOW MORE button in New York Times website?

**Comment by ChicoXYC** [comment]
@yaonuan1995 have you solve the questions? if not, please post your codes and questions here.

**Comment by hupili** [comment]
The issue is outdated.

For those interested minds, here's the solution: https://github.com/hupili/python-for-data-and-media-communication/blob/master/scraper-selenium/NYT.ipynb

This is a good practice of "human in the loop".

The data is here: https://github.com/hupili/python-for-data-and-media-communication/blob/master/scraper-selenium/nyt_world.csv
