### ISSUE TITLE
How to solve the 'UnicodeEncodeError' and the messy code problem?

### ISSUE THREAD

**Issue by coolxu8888** [hupili/python-for-data-and-media-communication-gitbook#66]
here are my codes:
```
import requests
from bs4 import BeautifulSoup
import csv

def scrape_onepage(purl):
    r = requests.get(purl).text
    data = BeautifulSoup(r,"html.parser")
    all_div = data.find('div',attrs={'class':"wrapper fixed"}).find_all("li")
    tittles=[]
    for i in all_div:
        tittle=[]
        tittle.append(i.find('div', attrs={'class':"t"}).find('strong').text.strip())
        tittle.append(i.find('div', attrs={'class':"w"}).text.strip())
        tittle.append(i.find('div', attrs={'class':"t"}).find('a')['href'])
        tittles.append(tittle)
    return tittles
def scrape_all_pages(url):
    page_urls=[]
    comments=[]
    for i in range(1,15):  
        if i == 1:
            url = 'http://www.chinabuildingcentre.com/list-41-1.html'
        else:
            url = 'http://www.chinabuildingcentre.com/list-41-{}.html'.format(i)
        page_urls.append(url)
    for purl in page_urls:
        comments.extend(scrape_onepage(purl))
    return(comments)
result = scrape_all_pages('http://www.chinabuildingcentre.com/list-41-1.html')


with open('cbc.csv','a',encoding='utf-8') as f:

    writer = csv.writer(f)
    header = ['titles','comment','url']
    writer.writerow(header)
    writer.writerows(result)
```

It runs ok, however, when you open the file in Excel, it goes wrong.

Before this problem,  I was soloving the unicode problem as follows:
```
with open('cbc.csv','w') as f:
    writer = csv.writer(f)
    header = ['titles','comment','url']
    writer.writerow(header)
    writer.writerows(result)
```

after excuted, it goes:

> ---------------------------------------------------------------------------
> UnicodeEncodeError                        Traceback (most recent call last)
> <ipython-input-142-9921ad8beff1> in <module>()
>     35     header = ['Titles','comment','Url']
>     36     writer.writerow(header)
> ---> 37     writer.writerows(result)
> 
> UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 17: illegal multibyte sequence

I google it and they told me is about the decoding and encoding problem, but I tried to add a parameter'encoding='utf-8''. It still can't be open by jupyternote book which tells me the csv file is not UTF-8 encoded. And when I tried to open it with Excel, it shows messy code again.
So, how can I solve these two problem?

**Comment by ChicoXYC** [comment]
<img width="981" alt="screen shot 2018-11-05 at 5 59 43 pm" src="https://user-images.githubusercontent.com/37010763/47991280-ae0d9c80-e124-11e8-8db3-879274b3513d.png">
@coolxu8888 you've done great job. The data is alright! `MAC OS's numbers` can open this file correctly.   I guess the the excel are not very supportive for the csv format. If you can see the file correctly display in GitHub, I think it should be fine.

**Comment by coolxu8888** [comment]
nice~
I'm really crying

**Comment by ChicoXYC** [comment]
Avoid encoding error with opening csv in Excel, please check out here 👉
https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/56bc1354cdc659950b0591a06ddce3e9140ceb6b/module-csv.md#encoding-issue-about-microsoft-excel
