### ISSUE TITLE
followed google sample code [Error using Youtube API]

### ISSUE THREAD

**Issue by elusiveburglar** [hupili/python-for-data-and-media-communication-gitbook#69]
# Troubleshooting

## Describe your environment
 
* Operating system: Windows
* Python version: 3.6
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?: 

## Describe your question

I used YouTube Analytics API sample code
https://developers.google.com/youtube/reporting/v1/code_samples/python
followed every step and the problem is 

![0_hc5wxnozcs0bymvo](https://user-images.githubusercontent.com/42874547/48049820-db1c8680-e1da-11e8-84a4-648a8c1814dc.png)
## The minimum code (snippet) to reproduce the issue

Example:

youtubeAnalytics = get_service()
  execute_api_request(
      youtubeAnalytics.reports().query,
      ids='channel==UCEf_Bc-KVd7onSeifS3py9g',
      startDate='2006-03-18',
      endDate='2018-11-06',
      metrics='estimatedMinutesWatched,views,likes,subscribersGained'
      dimensions='day',
      sort='day'
  )
  File "<ipython-input-1-717d3c3a3205>", line 37
    dimensions='day',
             ^
SyntaxError: invalid syntax

## Describe the efforts you have spent on this issue

Example:
i've constantly googled it but didn't find similar results.
!

**Comment by hupili** [comment]
Missing `,` at the end of `metrics` line.

**Comment by ChicoXYC** [comment]
@elusiveburglar have you solved the problem?

**Comment by elusiveburglar** [comment]
> @elusiveburglar have you solved the problem?

Sorry, I have switched another website so I didn't follow up.

**Comment by hupili** [comment]
Looks like coding error, instead of the usage of Youtube API. This issue is not for further discussion. Closing.
