### ISSUE TITLE
Feedback for Chapter 08

### ISSUE THREAD

**Issue by ConnorLi96** [hupili/python-for-data-and-media-communication-gitbook#72]
## Suggestions
- Histogram 
```df = pd.read_excel('nottingham.xlsx')``` When I try this code, there is module error. After system reminder, I install ```xlrd```, then it can work. I guess you can add it.

- Percentile
Maybe you can add the ```df["AVG_ENG_MATH_SCORE_10"].quantile(0.5)``` is equal to ```df["AVG_ENG_MATH_SCORE_10"].median()```, which can help us to understand the percentile better.

-  Continuous
Misspell in this sentence: For example, **```person```** measure the degree of the relationship between linearly related variables, while Spearman rank correlation is a non-parametric test. For more details

- Bonus: Better visualisation
```sns.regplot(df['P_ABSENT_PERSIST'], df['AVG_ENG_MATH_SCORE_09'])```
For this bonus, could you give more explanation why this visualisation is better than above one? Adding it in notes is alright.

- isna() & fillna()
I guess add some references or detailed explanation about this two functions will be better, it's a bit hard to understand. This[ link ](https://blog.csdn.net/lwgkzl/article/details/80948548)is useful. 

- Filter out in the charts
```s```  is not defined in your code.

## Conclusion: 
There are many new functions and concepts in this chapter, I guess a better way can help us learn it more efficiency is adding simple annotation like this ```# annotation ``` after new code.

**Comment by SerenaQYHuang** [comment]
> @SerenaQYHuang did you install the module regarded to the first question? I am not sure if this is really a question.

I didn't install because it was already installed in my environment

**Comment by ChicoXYC** [comment]
@ConnorLi96 test in the different environments, it should be installed first. 
Merged into notes. Thanks🎉🎉
