### ISSUE TITLE
Feedback for Note 08

### ISSUE THREAD

**Issue by SerenaQYHuang** [hupili/python-for-data-and-media-communication-gitbook#73]
When I was trying to run the following piece of code:
```
df['P_ABSENT_PERSIST'].hist(bins=20)
```
I did not get a histogram. Instead, I got this:
![image](https://user-images.githubusercontent.com/41979788/48137024-15ba1800-e2dc-11e8-88fa-a7b14024afd1.png)

**Comment by hupili** [comment]
You can put `%matplotlib inline` in the first cell, so the figure is inserted inline. 

If not working, try to execute that plotting cell twice -- seems a recent Jupyter notebook glitch.

**Comment by SerenaQYHuang** [comment]
> You can put `%matplotlib inline` in the first cell, so the figure is inserted inline.
> 
> If not working, try to execute that plotting cell twice -- seems a recent Jupyter notebook glitch.

Problem solved by adding ```%matplotlib inline```. Thank you so much!

**Comment by SerenaQYHuang** [comment]
Two comments on KDE: (for students to extend your mind)

1. 
```
ax = df['AVG_ENG_MATH_SCORE_10'].hist(bins=15)
df['AVG_ENG_MATH_SCORE_10'].plot(kind='kde', ax=ax, secondary_y=True)
```
![](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/assets/histogram-and-KDE.png)

What if we do not define ax here, but put it into the second line directly?

![image](https://user-images.githubusercontent.com/41979788/48184279-7abd4e80-e36c-11e8-9c83-7d8c0de46201.png)

As we can see, it also works. Based on my personal understanding, the latter might seem more efficient for a short piece of code; However, if we are writing a long piece of code, and if define ax in the first place, it can be used over and over again without typing in a long sentence. Thus, the latter is more recommended. I'm wondering if I've got the point here @hupili @ChicoXYC 

2. What if we leave the ax part blank here? I tested and the result was as follows.
Only KDE will be left.
![image](https://user-images.githubusercontent.com/41979788/48184500-2f577000-e36d-11e8-9579-eb8ce502f76c.png)

**Comment by SerenaQYHuang** [comment]
```
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE_10'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_9**'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_8**'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_7**'], method='spearman')
```
should be
```
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE_10'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_09**'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_08**'], method='spearman')
df['P_ABSENT_PERSIST'].corr(df['AVG_ENG_MATH_SCORE**_07**'], method='spearman')
```

**Comment by ChicoXYC** [comment]
@SerenaQYHuang for comments 1 and 2, you are totally right about this.
Thanks for the error you found in notes, I was keeping updating the notes today. Please refresh the notes and see if there is new content. Free to leave comments if there is further needs.

**Comment by SerenaQYHuang** [comment]
```
na_selector = df['P_ABSENT_PERSIST'].isna()
```
The ```isna()``` function is only for pandas version 0.22 and above. It is suggested that for students who have lower versions of pandas, use ```isnull()``` instead.

**Comment by SerenaQYHuang** [comment]
I'm wondering what this 's' means here... I don't think we have defined this
```
s.quantile(0.95)
df_cleaned[s > s.quantile(0.95)].plot(
    x='P_ABSENT_PERSIST', 
    y='AVG_ENG_MATH_SCORE_09', 
    kind='scatter')
```
Output:
NameError: name 's' is not defined
@hupili @ChicoXYC

**Comment by SerenaQYHuang** [comment]
```
def discretise(x):
    if x <= 1:
        x = 'hard_working'
    elif x > 1 and x <= 3:
        x = 'middle'
    elif x > 3:
        x = 'happy'
    return x
f = ['mean','max','min','var','std']
df['group'] = df['P_ABSENT_PERSIST'].apply(discretise)
year9_agg = yeardf.groupby('group')['AVG_ENG_MATH_SCORE_09'].agg(f)
year9_agg.sort_values(f,ascending=False)
```
The name 'yeardf' also was  not defined here

**Comment by SerenaQYHuang** [comment]
```
df.pivot_table(index=['grade_07','grade_08'], columns=['grade_10'], values='Schoolme', aggfunc='count')
rate = a / b
```
a and b not defined here

**Comment by SerenaQYHuang** [comment]
I have gone through all the note and all the questions are presented above

**Comment by ChicoXYC** [comment]
@SerenaQYHuang Also, can you help me to test in the other issue I mentioned here https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/72
