### ISSUE TITLE
How to compile different lists into CSV correspondingly?

### ISSUE THREAD

**Issue by CelineTsang** [hupili/python-for-data-and-media-communication-gitbook#74]
I crawled to the restaurant's name and address, tags and other information, I want to know how to put their corresponding into a table. Otherwise, the output data is independent.
<img width="650" alt="2018-11-07 10 47 52" src="https://user-images.githubusercontent.com/42716407/48139640-f0300d00-e2e1-11e8-8824-774cea2ecca2.png">

<img width="617" alt="2018-11-07 11 04 02" src="https://user-images.githubusercontent.com/42716407/48139476-8f083980-e2e1-11e8-80bc-8d774c97c0f1.png">
<img width="597" alt="2018-11-07 11 04 13" src="https://user-images.githubusercontent.com/42716407/48139502-9b8c9200-e2e1-11e8-988b-ff55a48853e9.png">

**Comment by warrior960812** [comment]
First You can create a new list of lists. For example:


```
All_information=[]
for i in range(len(names)):
      all_information = [names[0], tags[0]]
      All_information=all_information.append(all_information)
```

（then you got the list including names and tags)

Next, you can write the CSV:


```
with open('restaurants.csv', 'a', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='"', quoting=csv.QUOTE_MINIMAL)
    header= ["names", tags"]
    spamwriter.writerow(header)
    spamwriter.writerows(All_information)
```


(Because the writerows means you should print all the rows in the form of list, and  the All_information (the list we created) should includes all index of the names and tags.

**Comment by hupili** [comment]
`zip` function can come handy sometimes, but I strongly advise you to adopt the item-first/ then-attribute approach in scraping: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#item-first-vs-attribute-first

**Comment by ChicoXYC** [comment]
@CelineTsang have the problems solved?

**Comment by CelineTsang** [comment]
Thank u all. I already solved the problem!
