### ISSUE TITLE
about scraping 

### ISSUE THREAD

**Issue by CCCCCecilia** [hupili/python-for-data-and-media-communication-gitbook#75]
在抓取虾米网站数据时，会不定时出现禁止访问的问题。在网上找到的解决方案是要更换headers中的cookie, 有效但是要人为更换， 请问有没有其他的解决方法来解决该问题?

**Comment by ChicoXYC** [comment]
@CCCCCecilia can you post your codes here?

**Comment by CCCCCecilia** [comment]
@ChicoXYC  here [https://github.com/CCCCCecilia/python-data-assignments/blob/master/assignment1/assignment1.ipynb](url)

`import requests
from bs4 import BeautifulSoup
import time
import csv
base_url = "https://www.xiami.com/search?key="

headers = {
    'authority': 'www.xiami.com',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'referer': 'https://www.xiami.com/artist/top-O9fc383?spm=0.0.0.0.OC7hVH',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'zh-CN,zh;q=0.9',
    'cookie': '_uab_collina=154164839983364920692646; gid=154164548545184; PHPSESSID=3366038599e8126a51651882df8c106b; join_from=1zufSNtP6D010%2FjCCA; _xiamitoken=301a978ededcf778bc37949e5fb12191; _unsign_token=095abebc279a7d4b9558d8d378bbbf20; user_from=1; UM_distinctid=166f13b4b1ee21-0ed62f08a435d-1e396652-13c680-166f13b4b1f8e8; cna=1NNhFGAjzx0CAZ62vkePvgvJ; xm_expect_legacy=1; CNZZDATA921634=cnzz_eid%3D333370432-1541643654-null%26ntime%3D1541650739; CNZZDATA2629111=cnzz_eid%3D972414053-1541641074-null%26ntime%3D1541651595; x5sec=7b22617365727665723b32223a223565646430643734363238323339623466663635313334396531396439343430434d754c6a393846454c726576654f766f7179633377453d227d; isg=BNLSiKt63Y7z6SFyaCs543S0I550S9YREKVEbJwrxgVwr3OphHOejRhNGks2vU4V',
}


def get_albums_url(singer_name):
    r = requests.get(base_url+singer_name+"&pos=1",headers=headers)
    html_str = r.text
    soup = BeautifulSoup(html_str,"html.parser")
    albums = soup.find_all("a",attrs = {"class":"song"})
    for album in albums:
        ablum_name = album['title']
        print(ablum_name)
        album_url = album["href"]
        get_songs_url("https:" + album_url, singer_name)

def get_songs_url(album_url,singer_name):   
    r = requests.get(album_url, headers=headers)
    html_str = r.text
    soup = BeautifulSoup(html_str, "html.parser")
    songs_td = soup.find_all("td", attrs={"class": "song_name"})    
    for song_td in songs_td:
        song = song_td.find("a")
        # song_name = song.text
        # print(song_name)
        song_url = song["href"]
        get_song_info(song_url,singer_name)

def get_song_info(song_url,singer_name):
    r = requests.get("https://www.xiami.com"+song_url,headers=headers)
    html_str = r.text
    soup = BeautifulSoup(html_str, "html.parser")
    title = soup.find("div",{"id":"title"}).find("h1").text
    song_infos = soup.find("table",{"id":"albums_info"}).find_all("tr") 
    arranger = ""
    singer = ""  
    writer = ""
    composer = ""
    for i in range(0,len(song_infos)):    
        if i ==0:
            album = song_infos[i].find("a").text
        elif i==1:
            singer = song_infos[i].find("a").text
        elif i==2:
            writer = song_infos[i].find("div").text
        elif i==3:
            composer = song_infos[i].find("div").text
        elif i==4:
            arranger = song_infos[i].find("div").text
    try:
        lyric = soup.find("div",{"class":"lrc_main"}).text.replace("<br>"," ")
    except Exception as e:
        return
    music_count = soup.find("div", {"class": "music_counts"}).text.split("\n")
    share_num = music_count[3][:-2]
    comm_num = music_count[4][:-2]
    content = [title, album, lyric, singer, writer, composer, arranger, share_num, comm_num]
    print(content)
    with open(singer_name+'.csv', 'a', newline='',encoding="utf-8") as csvfile:
        mywriter = csv.writer(csvfile)

        mywriter.writerow(content)

def main():
    singers_name = ['周杰伦' , "陈奕迅" , '林俊杰' , '林宥嘉']
    for singer_name in singers_name:
        with open(singer_name+'.csv', 'w', newline='',encoding="utf-8") as csvfile:
            mywriter = csv.writer(csvfile)
            header = ["歌名", "专辑名","歌词", "演唱", "作词", "作曲", "编曲","分享数","评论数"]
            mywriter.writerow(header)
        print(singer_name)
        get_albums_url(singer_name)

main()
`
