### ISSUE TITLE
how to slice two elements under the same content when one of them may be None sometimes?

### ISSUE THREAD

**Issue by 18426425** [hupili/python-for-data-and-media-communication-gitbook#76]
# Troubleshooting

## Describe your environment

* Operating system:
* Python version: python3
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]: Y
* Which chapter of book?: 

## Describe your question

When scraping http://maoyan.com/board/4?offset=0, I want to slice the two elements: "release time" and "country" out respectively, but some movies show their country, some don't . for instance 
some are like this :
<p class="releasetime">上映时间：1993-01-01</p>
while some :
<p class="releasetime">上映时间：1994-10-14(美国)</p>

So my question is how to slice the "two" elements? btw, it seems that they belong to one string tightly.

**Comment by hupili** [comment]
string processing is needed. Try .split , in , endswith , etc

**Comment by ChicoXYC** [comment]
@18426425 For this case, I think the format of time is fixed, with 10 character length. Therefore, we can use list slicing to separate them.
![image](https://user-images.githubusercontent.com/37010763/48253547-7bc0af80-e442-11e8-9f2a-fdcebbfe308c.png)

**Comment by 18426425** [comment]
Yes, the problem has already solved under Pili's concise method, here are his codes: (starts from line 34 )
http://localhost:8888/notebooks/assignment1%20test.ipynb

**Comment by hupili** [comment]
Amber, we can not visit that URL. That is on your own computer. (localhost)

Can you put it on GitHub and paste the GitHub URL for others reference?

**Comment by 18426425** [comment]
### Here is the GitHub URL:
https://github.com/18426425/myexercise/blob/master/Assignment1%20Maoyan%20Movietest.ipynb

and I tried to find another way( by using "if...else", I counted the length of the shortest one and found 15 is the boundary value between "with country" and "without country")(see line 67), but I failed again...and still I don't think there is sth. wrong...

def get_country(x):
    **if len(time_countries) > 15:
        return x.split('：')[1].split('(')[1][:-1]
    else:
        return''**

df['country'] = df['time_countries'].apply(get_country)
df

**Comment by hupili** [comment]
good try. 

you can try to split the string first and test the boundary condition whether there are two fields or not

**Comment by ChicoXYC** [comment]
@18426425 have you solved the problem?

**Comment by 18426425** [comment]
Yes, thanks a lot, I have already solved the problem, "if...else" works, only if I delete a line of for loop:
**def get_country(x):
    if len (x) > 15:
        return x.split('(')[1].split(')')[0]
    else:
        return''
df['country'] = df['time_countries'].apply(get_country)
df**

and here is the whole codes:
https://github.com/18426425/myexercise/blob/master/Assignment1%20Maoyan%20Movietest.ipynb

**Comment by ChicoXYC** [comment]
merged into notes, please refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/frequently-asked-questions.md#data-extraction---slice-elements-when-one-of-them-may-be-none).
