### ISSUE TITLE
Week9_Data Viz Comments

### ISSUE THREAD

**Issue by rippleYJH** [hupili/python-for-data-and-media-communication-gitbook#78]
Here are three quick feedback for Week 9 notes:

1. For setting up the font part, the command "!open" doesn't work on my computer. I think it is because of the Window system. But we could try the command "matplotlib.get_cachedir()" , and it works.

2. I don't know why when I set the color, it sometimes raises such ValueError:
![image](https://user-images.githubusercontent.com/42017792/48472352-10575300-e831-11e8-8a6e-bcc02107d8b5.png)

3. When I executed the plotly, it will return with errors like this...

![image](https://user-images.githubusercontent.com/42017792/48472502-6deb9f80-e831-11e8-8687-1ec6ef4c1af5.png)

Thanks a lot if you can help me solve!

**Comment by ChicoXYC** [comment]
thanks. about question 2, where did it go wrong? and about question 3, I'm not sure what's happening here @hupili do you know this problem?

**Comment by rippleYJH** [comment]
`country_counts = df['country'].value_counts()[:15].sort_values(ascending=False)
country = pd.DataFrame(country_counts)
fig = plt.figure(figsize=(14,7))
plt.bar(country.index, country.country,color = '#46c99',edgecolor = '#40b4e5')`

But actually when I tried your codes, it works... So I have no idea why it raised a ValueError.

**Comment by SerenaQYHuang** [comment]
For the first question, I don't think there's such a command ```!open``` in Note09. Did you mean '!pip install' or open() ?

**Comment by FLYSTEPHEN** [comment]
- For question 2, since this is a [HEXcolor](https://zh.wikipedia.org/wiki/网页颜色), we can only set the code from  #000000 to #ffffff.
- For question 3, we can click into the url to register and follow the instructions, then the library will work.

**Comment by ChicoXYC** [comment]
update the plotly offline method, which does not require an account. please see [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-09.md#plotly).
