### ISSUE TITLE
Chapter 13: Geographical data

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#82]

**Comment by hupili** [comment]
@ChicoXYC , following maps can be added to the case study section:

- [ ] http://nbviewer.jupyter.org/github/kaiwenxu94/python-data-assignments/blob/master/assignment2/Assignment2-v2.ipynb  -- note that the map on NBViewer is not interactive, one can "open in new tab" to see the interactive version.

If you find other maps drawn by new libraries (not covered by our current case study), feel free to recommend links here.

**Comment by hupili** [comment]
@ChicoXYC 

- [ ] This screenshot is too large. Can adjust aspect ratio: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-13.md#england-and-ireland-pubs-using-matplotlib

**Comment by ChicoXYC** [comment]
update
