### ISSUE TITLE
The mode of data

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#88]
https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-08.md#the-mode-of-data

i.e. 众数

**Comment by ChicoXYC** [comment]
update https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-08.md#the-mode-of-data

**Comment by hupili** [comment]
Additional notes added.
