### ISSUE TITLE
Coding problems when reading CSV files

### ISSUE THREAD

**Issue by Zmh951010** [hupili/python-for-data-and-media-communication-gitbook#91]
## Working environment
* Operating system: windows 10
* Python version: 3.7
* Jupyter notebook or not?: yes

## Problem: cannot read a csv file downloaded from a website

I downloaded a csv file from a database, named 'HK_REITS_portfolio.csv', it includes traditional Chinese characters, dates and numbers and looks like this:
![image](https://user-images.githubusercontent.com/42828826/48826001-1c4c9300-eda4-11e8-8391-0936055d9171.png)

I want to draw a bar chart of several columns of this table but I was stuck at the first step,  my initial python code was:

```python
import pandas as pd
df = pd.read_csv('HK_REITS_portfolio.csv')
```
and the file cannot be read, the error was:
![image](https://user-images.githubusercontent.com/42828826/48826342-f5429100-eda4-11e8-8db2-b841f12ec2ce.png)

## Failed attempts
* Firstly I added this line at the beginning of the code, but it didn't help, same error
```python
# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv('HK_REITS_portfolio.csv')
```
* Then I tried to encode it, still didn't work, same error
```python
# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv('HK_REITS_portfolio.csv', encoding = 'gbk')
```
* Also tried 'rb', this time it can be read but not the correct form
```python
# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv('HK_REITS_portfolio.csv', 'rb')
```
![image](https://user-images.githubusercontent.com/42828826/48826611-bd881900-eda5-11e8-90f3-5a85c6778d94.png)

So I guess this is a problem of the original file

## Solution
Finally, I tried to copied and pasted the contains to Google drive, and downloaded it as a new csv, this time it can be successfully read.
![image](https://user-images.githubusercontent.com/42828826/48827201-874b9900-eda7-11e8-9209-9bffeda8f957.png)

![image](https://user-images.githubusercontent.com/42828826/48827211-93375b00-eda7-11e8-80aa-d1fb9ac80911.png)
![image](https://user-images.githubusercontent.com/42828826/48827235-ab0edf00-eda7-11e8-829b-bfc351ae3886.png)

![image](https://user-images.githubusercontent.com/42828826/48827249-b530dd80-eda7-11e8-84cd-7ddc2da34e7e.png)

```python
# -*- coding: utf-8 -*-
import pandas as pd
df = pd.read_csv('REITs.csv', 'rb')
```

![image](https://user-images.githubusercontent.com/42828826/48827399-22447300-eda8-11e8-86e8-a31e4ca03d86.png)

**Comment by ChicoXYC** [comment]
Merged into notes, you can refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/frequently-asked-questions.md#cannot-read-a-csv-file-downloaded-from-a-website).
