### ISSUE TITLE
problem about Pyecharts 

### ISSUE THREAD

**Issue by CCCCCecilia** [hupili/python-for-data-and-media-communication-gitbook#93]
* Operating system:MAC OS
* Python version:3.7.0
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?:WEEK9

##question 1: I draw a chart with Pyecharts. It can show in my Jupyter notebook, but cannot show when I use GitHub or https://nbviewer.jupyter.org to view it.
![1542813440113](https://user-images.githubusercontent.com/43194916/48851335-bed93600-ede5-11e8-98e5-62ab83a7aebd.jpg)
![1542813694854](https://user-images.githubusercontent.com/43194916/48851345-c7317100-ede5-11e8-8322-6fa35bad6ad6.jpg)

##another question: how can I change the color and theme of charts to keep all the charts color harmonious?

**Comment by hupili** [comment]
> ##question 1: I draw a chart with Pyecharts. It can show in my Jupyter notebook, but cannot show when I use GitHub or https://nbviewer.jupyter.org to view it.

Can you show the notebook link for our online testing? [more](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/pro-tips.md#asking-questions-like-a-pro)

> ##another question: how can I change the color and theme of charts to keep all the charts color harmonious?

Is this helpful? http://pyecharts.org/#/zh-cn/charts_style

**Comment by CCCCCecilia** [comment]
https://nbviewer.jupyter.org/github/CCCCCecilia/python-data-assignments/blob/master/assignment2/assignment2.ipynb

**Comment by CCCCCecilia** [comment]
> > ##question 1: I draw a chart with Pyecharts. It can show in my Jupyter notebook, but cannot show when I use GitHub or https://nbviewer.jupyter.org to view it.
> 
> Can you show the notebook link for our online testing? [more](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/pro-tips.md#asking-questions-like-a-pro)
> https://nbviewer.jupyter.org/github/CCCCCecilia/python-data-assignments/blob/master/assignment2/assignment2.ipynb
> > ##another question: how can I change the color and theme of charts to keep all the charts color harmonious?
> 
> Is this helpful? http://pyecharts.org/#/zh-cn/charts_style

**Comment by hupili** [comment]
For the pyecharts rendering problem, you can try the following steps:

1. Save the chart to standalone HTML files.
2. Use the `from IPython.display import IFrame` way to load it into your notebook.

Reference to the map in my recent [open rice map visualisation](https://nbviewer.jupyter.org/github/hupili/openrice-data-blog-201811/blob/master/12.%20Sichuan%20Map.ipynb)

Please let us know if this works.

**Comment by CCCCCecilia** [comment]
> For the pyecharts rendering problem, you can try the following steps:
> 
> 1. Save the chart to standalone HTML files.
> 2. Use the `from IPython.display import IFrame` way to load it into your notebook.
> 
> Reference to the map in my recent [open rice map visualisation](https://nbviewer.jupyter.org/github/hupili/openrice-data-blog-201811/blob/master/12.%20Sichuan%20Map.ipynb)
> 
> Please let us know if this works.

I tried this solution and it worked. Now the chart can show on nbviewer, but still cannot show on GitHub .

**Comment by CCCCCecilia** [comment]
> @CCCCCecilia can you show the working solution and help @ChicoXYC to merge into the FAQ? Thanks.

OK.

**Comment by ChicoXYC** [comment]
merged into notes: https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-jupyter.md#import-interactive-charts-in-jupyter-notebook
