### ISSUE TITLE
How to loop in different format {} 

### ISSUE THREAD

**Issue by lullabymia** [hupili/python-for-data-and-media-communication-gitbook#96]
# Troubleshooting

## Describe your environment

* Operating system: mac
* Python version: 3.7
* Hardware: macbook
* Internet access: http://paper.people.com.cn/rmrb/html/2008-10/27/nbs.D110000renmrb_01.htm
* Jupyter notebook or not? [Y/N]: Y
* Which chapter of book?: 

## Describe your question
I am scraping articles from people's daily 
I want to 
1. find different articles, 
2. turn pages (4 pages)
3. change the dates 
at the same time.
But how can I do it with .format() if the number for each purposes is different. 
And one of them is not a fixed number, since there might be 4/5/6/7 articles articles) .

## The minimum code (snippet) to reproduce the issue

Example:

```python
def gettext(url):
    import requests
    r=requests.get(url)
    r.encoding = 'utf-8'
    import bs4
    mypage = bs4.BeautifulSoup(r.text)
    text = mypage.find(attrs={'class': 'text_c'}).text.strip()
    return text 
for i in range (1,9):
    url = "http://paper.people.com.cn/rmrb/html/2008-10/27/nw.D110000renmrb_20081027_{}-01.htm".format(i)
    onepage = gettext(url)
    print(onepage)

```

<img width="660" alt="2018-11-22 3 05 31" src="https://user-images.githubusercontent.com/42403858/48886834-57b09580-ee68-11e8-9ea2-30316101598c.png">

**Comment by lullabymia** [comment]
It seemed that I successfully turned pages and dates, but it kept raising errors. I know it is because the number of articles differs from every page. How can I solve it? 
Also, I am supposed to start from the first date of October, but I don't know how to  start from 01 to 31.
```python
def gettext(url):
    import requests
    r=requests.get(url)
    r.encoding = 'utf-8'
    import bs4
    mypage = bs4.BeautifulSoup(r.text)
    text = mypage.find(attrs={'class': 'text_c'}).text.strip()
    return text 

c = 10
while c < 32:

    a = 1
    while a < 7:
        for b in range(1,5):
            url = "http://paper.people.com.cn/rmrb/html/2008-10/{2}/nw.D110000renmrb_200810{2}_{0}-0{1}.htm".format(a,b,c)
            onepage = gettext(url)
            
            
            print(onepage)
        a = a + 1
    c = c + 1
```

<img width="742" alt="2018-11-22 9 13 51" src="https://user-images.githubusercontent.com/42403858/48905099-8dbb3d00-ee9b-11e8-9858-996716c8f57f.png">

**Comment by ChicoXYC** [comment]
@lullabymia Nonetype means that it doesn't find the text you want, mostly because there might be no text. Following is the debugging process.

1. please first format all the URLs you want, append into a list.
2. find elements in a single page. If works, then for loop all the URL lists to get more.
3. For handling none type error when scraping, please refer the following method, and you can checkout the error cases later.

```python
    try:
        #your scraping codes here
    except Exception as e:
        print(e)
        print('Error on page %s' % i)
```

**Comment by lullabymia** [comment]
@ChicoXYC problem solved! Thank you!

**Comment by ChicoXYC** [comment]
Closed. You can refer to the [Item-first v.s. attribute first](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-05.md#item-first-vs-attribute-first) And handle errors by [Try sub-tasks and regroup success/ fail cases](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-03.md#try-sub-tasks-and-regroup-success-fail-cases) for further explanation.
