### ISSUE TITLE
cannot run Chinese words 

### ISSUE THREAD

**Issue by shiyuning0987** [hupili/python-for-data-and-media-communication-gitbook#98]
# Troubleshooting

## Describe your environment

* Operating system:mac
* Python version:3.7
* Hardware:mac book
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?:week09

## Describe your question
cannot find SimHei foot in my computer

![image](https://user-images.githubusercontent.com/42941700/48903398-6a41c380-ee96-11e8-8882-0818025d9743.png)

sns.set(font='SimHei')
## Describe the efforts you have spent on this issue

Example:

### Have you Google/ Stackover flow anything?
yes and download the simhei.ttf
### Do they solve or partially solve your question?
not really ,it's all help with python 3.7
### What is the closest answer you can find?
https://blog.csdn.net/Fantasy_Muse/article/details/78585049

**Comment by hupili** [comment]
Can you put up the notebook?

**Comment by shiyuning0987** [comment]
yes！here is the link
https://github.com/shiyuning0987/python-data-assignments/blob/master/assignment2.ipynb

**Comment by shiyuning0987** [comment]
use this link
https://github.com/shiyuning0987/python-data-assignments/blob/master/assignment2-Copy1.ipynb

**Comment by hupili** [comment]
@shiyuning0987 , please try to resolve Chinese with matplotlib first:  https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-matplotlib.md  

When you can use `matplotlib`'s `plt.plot` to show Chinese characters, `seaborn` should also work. Let's followup if the former half works but not the latter half.

You may want to load fonts and make sure `matplotlib` works with Chinese, before importing seaborn.

**Comment by ChicoXYC** [comment]
@shiyuning0987 have you solved the problem? if no, please let us know.
