### ISSUE TITLE
I can't scrap all the data in one page

### ISSUE THREAD

**Issue by AlexZenghuashan** [hupili/python-for-data-and-media-communication-gitbook#99]
# Troubleshooting

## Describe your environment

* Operating system:
* Python version:
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]: Y
* Which chapter of book?:

https://github.com/AlexZenghuashan/repo/blob/master/%E4%BA%BA%E4%BA%BA%E4%BA%A7%E5%93%81%E7%BB%8F%E7%90%86.ipynb

## Describe your question

The key puzzle is that if you grab a page you can only grab the first one but I've already written the loop and if you run it alone you can grab all the objects on a page.

![image](https://user-images.githubusercontent.com/42838093/48909458-4be4c380-eea8-11e8-8b8f-f30a06308ef8.png)

## The minimum code (snippet) to reproduce the issue

Example:

```python
open('path-to-a-file-not-exist')
```

## Describe the efforts you have spent on this issue

Example:

### What is the closest answer you can find?

**Comment by ChicoXYC** [comment]
@AlexZenghuashan Please refer here: https://github.com/ChicoXYC/exercise/blob/master/student-cases/element-first%26multiple-layer.ipynb and let me know if helps

**Comment by AlexZenghuashan** [comment]
Thank you! My problem has been solved.
